### ISSUE TITLE
Documentation on enabling palm rejection with toshy (Question) 

### ISSUE THREAD

**Issue by bennyweise** [RedBearAK/toshy#148]
First, love your work on this project - I'm trying to move as much as possible to working on Linux, but sane keyboard shortcut configuration is an absolute show stopper for me, so this is a life saver! One thing I found that was frustrating until I realised what was happening:
- palm rejection is disabled by default on virtual keyboards (at least on 23.10). Palm rejection isn't great coming from a Mac to a new Framework laptop, but without it was almost impossible to type. Because it was a new laptop I had no experience on, I only realised it was a software issue when I was killing toshy to deal with #147 . I eventually figured out how to enable palm rejection through libinput configuration, but it was a hit and miss process. Would you consider it useful to have some documentation about this? I think I've documented it somewhere, and would be happy to add this to the docs.
- another thing I would like some guidance on. I'm using the tactile gnome extension for window management, and finding global shortcuts that work across all app types can be a bit of a pain (e.g. for launching the window manager). Are there more efficient ways to see how different key combinations are handled across different app types?

**Comment by RedBearAK** [comment]
@bennyweise 

>  Would you consider it useful to have some documentation about this? 

Absolutely. I didn't realize this was a problem in the first place, much less a solvable problem. If it's something that could be made universal I might even make a script tool for it. Eventually. 

> I'm using the tactile gnome extension for window management, and finding global shortcuts that work across all app types can be a bit of a pain (e.g. for launching the window manager). 

Yes, that is difficult. 

What matters from the perspective of Toshy is that Meta/Super/Win (different names for the same key code) moves over to the physical Ctrl key, and then vanishes in "terminal" apps (becomes LEFT_CTRL) so if you're going to attempt to do a tiling shortcut that works in both GUI apps an terminal apps there would need to be two different remaps for each shortcut. Unless the shortcut is actually set to Super+Something in the desktop environment, then you'd only need the remap for terminal apps to make that work. 

I've never really had good luck supporting even the simpler workspace navigation shortcuts. They are different in each desktop environment, and there's not much from macOS to try to standardize on. 

I can try to help you make some custom shortcuts work. I recommend putting overrides or custom shortcuts in keymaps in the "User Apps" section, within some of the "slice marks" that will allow the custom lines to survive a re-install of Toshy. 

You'd want some keymaps in there that look like this: 

```py
keymap("User overrides terminals", {

}, when = matchProps(lst=terminals_lod))
keymap("User overrides general", {

}, when = matchProps(not_lst=remotes_lod))
```

The first one would add remaps that would activate in any terminal app, the second has the same conditional as the "general" keymap that contains shortcuts that remain active in all apps while Toshy is running.

**Comment by bennyweise** [comment]
Great, thanks for the info on custom shortcuts. I ended up going down the path of using super+random key to activate tactile, which works well enough for me at the moment. I've previously used the inbuilt tile left/right/full screen shortcuts and overloaded them, but I found I was desperately looking for a tile 2/3 which isn't an option, hence moving to tactile.

I'll try to find my notes (they are eluding me at the moment), but the TLDR is that libinput only associates real internal keyboards with palm rejection, so there's additional configuration required to tell it to apply palm rejection to the keyszer virtual keyboard. It's a pretty simple change, just adding

```/usr/share/libinput/60-local-toshy.quirks
[Serial Keyboards]
MatchUdevType=keyboard
MatchName=Keyszer (virtual) Keyboard
AttrKeyboardIntegration=internal 
```

I've no idea across what distros this would work, and there might have been some other steps required.

**Comment by RedBearAK** [comment]
@bennyweise 

FYI: I just forked `keyszer` into a new repo called `xwaykeyz`, and renamed most of the references to `keyszer` inside that repo to `xwaykeyz`. That will include the identity of the virtual keyboard, which will now come out as: 

```
XWayKeyz (virtual) Keyboard
```

If you were to reinstall Toshy from a new zip starting today you may need to update your palm rejection fix, if it's based on matching the keyboard device name. New installs of Toshy will no longer be cloning from the special development branch in my own fork of `keyszer`, but rather cloning from this new `xwaykeyz` repo. Aside from the name it is identical to the current state of the `keyszer` branch I've been using. 

I would like to add a Wiki page at some point explaining how to do this palm rejection fix, if you can flesh it out a little bit with a better description of the steps involved.

**Comment by bennyweise** [comment]
Thanks, great timing for the prompt. I'm just in the process of re-installing ubuntu on my laptop, so I need to go through the process again. Do you want me to document it in this issue? Or is there a better place to do it for now?

**Comment by RedBearAK** [comment]
Let’s just lay it out here first.

**Comment by bennyweise** [comment]
@RedBearAK here is write up of the steps I have taken - let me know if there are bits that aren't clear.


## Enabling palm rejection with Toshy

Note: this guide has been created using a laptop running Ubuntu 23.10. It may work or require modifications with other laptops.
If you have installed Toshy on a laptop, you may notice that palm rejection is disabled when you start toshy services (i.e. you will get random trackpad movement and taps register while typing, which can change window focus and do other annoying things).

The underlying cause is that in Gnome (at least for standard setups), palm rejection is only enabled for internal keyboards, and the virtual keyboard created by toshy is not marked as internal. We can change this by adding a quirk to libinput (the driver that handles most input devices).

## Confirming libinput handles your keyboard input

By default Ubuntu uses libinput, but other distros may use something else. Running `lsinput` or `xinput` and `xinput list-props <id>` might give some indication, but I don't yet have a reliable way of determining this. (For instance, on my AMD laptop I can't confirm the driver, but on my desktop running lsinput mentions libinput as the driver).

## Modifying libinput quirks

Firstly, you may need to install the libinput command line tools:

```
sudo apt install libinput-tools
```

This provides the `libinput` CLI tool which can be used to verify that you have created the device quirk properly.

Next, as root create a local overrides quirk (following the instructions [here](https://wayland.freedesktop.org/libinput/doc/latest/device-quirks.html#installing-temporary-local-device-quirks)). 

```sh
sudo mkdir /etc/libinput
sudo vim /etc/libinput/local-overrides.quirks
```

Add the following to the file:

```local-overrides.quirks
[Toshy Virtual Keyboard]
MatchUdevType=keyboard
MatchName=XWayKeyz (virtual) Keyboard
AttrKeyboardIntegration=internal
```

Take careful note, trailing spaces or any other formatting issues will cause the quirks parser to fail (and may affect over quirks as well). Also, if you are running an old version of toshy, replace `XWayKeyz` with `Keyszer`. You can confirm the name of the device by running `libinput list-devices`.

We can verify that the quirk is parsed correctly by running `libinput list-devices`, finding the correct device kernel in the output (which will look like `/dev/input/eventXX`), and running 
```sh
libinput quirks list /dev/input/eventXX
```
You should see `AttrKeyboardIntegration=internal` in the output. At this stage the driver hasn't actually loaded the quirk - this requires a restart. (It may be possible that logging out and in would also work, but hasn't been tested).

**Comment by RedBearAK** [comment]
Outstanding write up so far. However I’m wondering if instead of doing this:

```
[Toshy Virtual Keyboard]
MatchUdevType=keyboard
MatchName=XWayKeyz (virtual) Keyboard
AttrKeyboardIntegration=internal
```

 It might not be better to do this:

```
[XWayKeyz Virtual Keyboard]
MatchUdevType=keyboard
MatchName=XWayKeyz (virtual) Keyboard
AttrKeyboardIntegration=internal

[Keyszer Virtual Keyboard]
MatchUdevType=keyboard
MatchName= Keyszer (virtual) Keyboard
AttrKeyboardIntegration=internal
```

If that’s possible. It’s really the keymapper that is creating the virtual keyboard device, not Toshy. Having both device names should cover users with older installs and newer installs with less confusion.

**Comment by bennyweise** [comment]
That should work - although just note that there's a leading space in the Keyszer MatchName which might cause a problem. I believe you could also just to

```
MatchName=*(virtual) Keyboard
```
to catch both (currently untested).

**Comment by RedBearAK** [comment]
Fixed. A test of the wildcard match would be nifty. 

This should make for a good Wiki page once I have more time to look it over and maybe test it myself. 

Really appreciate you taking the time to put this together.

**Comment by bennyweise** [comment]
I've just tested the wildcard match, and that seems to work for me.

**Comment by RedBearAK** [comment]
> I've just tested the wildcard match, and that seems to work for me.

Thanks for testing it.

**Comment by RedBearAK** [comment]
Look over the Wiki page at your leisure. It's rearranged just a bit, with a few minor edits, but mostly just copy and paste. 

https://github.com/RedBearAK/toshy/wiki/How-to-enable-palm-rejection-on-virtual-keyboard

If you think that does the job providing some usable documentation, you can probably close this issue out if you want. 

Given how common `libinput` is, I suspect the instructions will work on quite a few modern Linux distros.

**Comment by RedBearAK** [comment]
Actually, what do you think about having the virtual keyboard always marked as "internal", especially if I can enable this from inside the keymapper when the device is created? 

Also, I wonder, since this device is created when the keymapper is started, shouldn't the quirks setting take effect as soon as the keymapper is restarted? Do you find that you have to restart your system to enable the quirk?

**Comment by RedBearAK** [comment]
GPT-4 (the smarter one) seems to think I can just add a new `udev` rule to take care of this: 

```udev
ACTION=="add", KERNEL=="event*", ATTRS{name}=="*\(virtual\) Keyboard", ENV{ID_INPUT_KEYBOARD}="1", ENV{ID_INPUT_KEY}="1", ENV{LIBINPUT_ATTR_KEYBOARD_INTEGRATION}="internal"
```

Since I already have to use a `udev` rules file, it would not be a big deal to add this.

**Comment by RedBearAK** [comment]
The attempt to use a `udev` rule didn't seem to work out, in a Neon virtual machine. No idea why, currently. So we'll just have to rely on these `libinput` quirks instructions for now.
