### ISSUE TITLE
OSX key maps not active? 

### ISSUE THREAD

**Issue by chris-hailstorm** [RedBearAK/toshy#177]
Hi, new user here. Toshy seems like a great idea, however it's not working for me. I may be confused.

After setting up Toshy, should I expect OSX ⌘ commands to work? For example I would expect ⌘-T to open a new browser or terminal tab, and ⌘-W to close one, but they don't. Toshy is installed and working -- if I make small changes to the config file and restart, my changes are in effect.

Is there a sample config that implements the OSX key maps? Or am I expecting too much.

**Comment by RedBearAK** [comment]
@chris-hailstorm 

That’s exactly what the standard config is supposed to do. Make everything work like macOS. 

What distro and desktop environment are you using? This matters, especially with any Wayland session. 

What happens when you try the diagnostic shortcut? Shift-Opt-Cmd-I,I (quickly double tap the “I” key while holding the mods. 

What changes were you testing in the config file that worked, and what app(s) did they work in?

**Comment by RedBearAK** [comment]
@chris-hailstorm 

BTW, I don't really understand this line: 

> Is there a sample config that implements the OSX key maps? Or am I expecting too much.

If you are able to open the config file and make changes, and they seem to take effect, you should be seeing the whole default Mac-like modmaps and keymaps in that default config file. The default config file is around 4K lines long now. 

You are using the Command-key symbol, but if you aren't using an Apple keyboard the keyboard may be getting misidentified. Have you tried using the key in the position of the Apple Option key instead of Command? It would be odd for an Apple keyboard to be misidentified, but it's possible. 

I can't really know what's happening without more information.

**Comment by chris-hailstorm** [comment]
I'm running this on Ubuntu 23.10, using x11. The diagnostic leystroke shows the class and title of this window, and also `Keybd = 'Razer Razer BlackWidow V3 Tenkeyless'`.

The changes I tested were small isolated changes, just so I could be sure I was looking at the right config file. For example, in the General GUI section, I changed `C("Alt-Tab"): ignore_combo` to use `C("Super-Tab")`, and that worked. The told me I'm working in the right config file. (And I reverted that change).

I think maybe I'm expecting the wrong behavior. My assumptions was that all ⌘ keystrokes from the Mac would work with the ⊞ symbol on my Razer keyboard. Examples of what's happening: (1) in multiple apps (I checked Firefox, Nautilus, and VS Code), ⊞-W inserts a ∑ character instead of closing the tab / window -- but Alt-W does close the tab / window; (2) in Gnome-terminal, ⊞-W doesn't do anything -- the terminal's default shortcut of Ctrl-Shift-W is what close a tab;  (3) App switching is via Alt-Tab instead of ⊞-Tab.

Maybe I'm wrong in assuming that generally ⊞ is the substitute for ⌘? That would explain some of this, but not the Gnome-terminal behavior.

Thanks for your help.

**Comment by RedBearAK** [comment]
Forget what the symbols are on the modifier keys and just pretend you are using an Apple keyboard. The key in the same physical location as the Command key should do what you would normally expect the Command key to do on a Mac. 

The unusual character is part of the normal special character set you get from an Apple keyboard in macOS when holding Option or Shift-Option. 

Same should apply to the terminal. On a Windows style keyboard Alt-T should open new tabs, Alt-W should close tabs. Several common shortcuts like this are remapped onto the Shift-Ctrl combos that terminals expect to see. 

As long as the keyboard type is identified correctly by the automatic algorithm, the keyboard should act (physically) like it is an Apple keyboard. From your description it sounds like this is exactly what is happening. You’re just overthinking it a bit and not allowing the magic to happen. 🤞

The way things work behind the scenes is a little unintuitive. For instance the key next to the Space bar becomes RIGHT_CTRL, not what you might expect, which would be Meta/Super/Win/Cmd (all the same key code). So when you see “RC” in the config file, think of it as the Command key physical position. And outside of terminals the physical Ctrl key becomes the Meta/Super/Win key. But you would normally only need to understand this if you need to add your own custom shortcuts or a new keymap. 

Let me know if this helps.

**Comment by RedBearAK** [comment]
Also there is a Wiki page showing how to fix some shortcuts in the embedded VSCode terminal. This has to be done inside each VSCode-like app due to limitations of the keymapper. 

https://github.com/RedBearAK/toshy/wiki/Embedded-terminal-in-VSCode-and-variants

**Comment by RedBearAK** [comment]
@chris-hailstorm 

Bump. Still having issues with the modifiers?

**Comment by Merkie** [comment]
I am also getting the same issues this person has mentioned here. So with Kinto, it worked 100% amazing I loved it but the one place it fell short for me was selecting text (which is where I found your replies). So now I uninstalled Kinto, I actually tried to get Keyszer working a few times with Kinto but failed every time. So then I found Toshy and the install script worked great like it says its running but my CMD key isnt working like Kinto had it. With Kinto I'd also tap my left alt key in the setup so technically I've been using my left alt as command, which if I could have that here that would be great. But right now CNTRL is working like CMD so CNTRL + N makes a new window, whereas I want it to be Left Alt + N or CMD + N. Also, the text selection doesn't work like MacOS/Kinto, CMD + left/right Arrows (for me it's CNTRL but I'm assuming it was written to be CMD) skips words where it should skip to the beginning and end of the line. ALT + arrows doesn't do anything. So at this point I need to remap CNTRL to Left Alt, and somehow get the arrows to skip lines... if that's even possible... Please let me know! I'd really really really love to bring over all this muscle memory to Linux lol. Kinto works fine but you need to let go of all modifiers before expanding/contracting your text selection in a different way. I am using Kubuntu LTS with KDE Plasma X11

**Comment by RedBearAK** [comment]
@Merkie 

I think you're having a different problem than the original submitter in this thread. Sounds like Toshy isn't even working at all, which is odd. 

I need a lot more information about your system. Try to run this command and show the output here (use code block formatting for things you paste from the terminal, if you know how). 

```sh
toshy-env
```

I just want to make sure that Toshy is seeing the environment info that it should. 

Then run this, and try to paste or attach the log output from the beginning, after you try to use a few shortcuts like Cmd+T (new tab) in the terminal. 

```sh
toshy-config-verbose-start
```

And show me the output from this command also, after you do the verbose log. You can do this in a separate terminal window or tab while leaving the verbose output running. 

```sh
toshy-services-log
```

**Comment by RedBearAK** [comment]
@Merkie 

I didn't have any difficulty installing Toshy in a fresh Kubuntu 22.04.4 LTS virtual machine. So there is something funky going on with your Kubuntu. It should work, even if it's Kubuntu 20.04 LTS, not 22.04 LTS. Or any of the recent non-LTS versions. 

Get back to me and we can try to figure out why it isn't working for you.

**Comment by RedBearAK** [comment]
@chris-hailstorm @Merkie 

I’ll be closing this soon if there are no further responses, since I can’t identify or fix any actual problem without more information.
