### ISSUE TITLE
Doing it wrong?

### ISSUE THREAD

**Issue by pierrenel** [RedBearAK/toshy#235]
Hi there!

I can see Toshy is running (in the GUI) - but .. strangely, to create a new tab in a browser etc I have to hit (the equivalent of) option T, not cmd T like in Macos? I've used Kinto in the past fwiw, keen to get Toshy working instead :)

**Comment by RedBearAK** [comment]
@pierrenel 

What kind of keyboard do you have? Something with both Windows and Mac modes? 

You can try temporarily overriding the keyboard type in the tray icon menu. Try the Apple type.

**Comment by RedBearAK** [comment]
@pierrenel 

If forcing it to be temporarily treated as the Apple keyboard type works, you'll need to get the device name and place it in a custom "dictionary" inside the config file, as described in the README. Then save the config and restart Toshy services from the tray icon menu. 

Get the device name with the diagnostic shortcut `Shift-Opt-Cmd-I,I` (the "I" key must be double-tapped quickly while holding the modifiers). Or, use the `toshy-devices` command in the terminal to see the full list. Which one is your keyboard is usually easy to pick out. 

If the keyboard only has one mode and the config file just needs to be able to identify correctly, we can also place the device name in the default Toshy config and then it would work correctly for everyone from then on. 

But if it's a multi-mode or custom keyboard you'll just have to stick to putting the device name in the editable slice for this. 

It looks like this: 

```py
###################################################################################################
###  SLICE_MARK_START: kbtype_override  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE

keyboards_UserCustom_dct = {
    # Add your keyboard device here if its type is misidentified.
    # Valid types to map device to: Apple, Windows, IBM, Chromebook (case sensitive)
    # Example:
    'My Keyboard Device Name': 'Apple',
}

###  SLICE_MARK_END: kbtype_override  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

Like the comment lines say, changes to the config file outside the special marks will be lost if Toshy is reinstalled at any point. But inside the marks the changes should be retained.

**Comment by pierrenel** [comment]
@RedBearAK thanks so much for the info - I've got an Anne Pro 2, with my keys mapped to match a mac keyboard - I'll give your instructions a whirl and report back!

**Comment by RedBearAK** [comment]
I will close this soon as resolved unless there is further input.
