### ISSUE TITLE
Key mapping of reverse search on terminal app seems to be counter-intuitive

### ISSUE THREAD

**Issue by ewh0** [RedBearAK/toshy#269]
First of all, I'm very grateful to your efforts for making this awesome tool. I've used kinto for long time and after the switch so far toshy is giving me an even better experience. Everything works out-of-box and is like a charm. It's a pity that this tool is not available on Windows.

So far I mainly notice one issue that seems to be counter-intuitive: Toshy seems to assign the key sequence "cmd + r" to the reverse search on terminal app. Normally people will invoke it by pressing "ctrl + r", but with Toshy I have to press "cmd + r" to make it works. 

OS: Fedora 39
Keyboard: Logitech K380 (the model supports both Win/Mac)

On K380, the "ctrl" modifier key is located at the bottom left corner of the keyboard (here is an example layout https://resource.logitech.com/content/dam/logitech/en/products/keyboards/multi-keyboard-k380/gallery/k380-sand-gallery-1-us.png) . The other key (cmd for Mac/alt for Win) is located left next to the space key. 

If I want to do a reverse search, I would actually need to press down "cmd/alt + r" instead of "ctrl + r". The position of "cmd/alt" on K380 is quite different from the position of "ctrl" key on the apple magic keyboard, which I often make it wrong as the long term muscle memory has already been built.

Is the current key mapping the expected behavior or this is specific to the keyboard that I'm currently using?

**Comment by RedBearAK** [comment]
@ewh0 

I'll be closing this issue soon unless there is further feedback. Other than applying the information in the Wiki page I linked previously, I don't think there's much I can do about the issue.
