### ISSUE TITLE
README: Table of Contents

### ISSUE THREAD

**Issue by 51n7** [RedBearAK/toshy#34]
**Is your feature request related to a problem?**
Sure isn't but finding key information would be a lot easier. I love all the detail though!

**Describe the solution you'd like**
Adding a table of contents to the start of the README.

**Comment by RedBearAK** [comment]
There is actually an automatic table of contents (with search even!) that GitHub adds at the upper left corner of the README "box" on the main page. Pretty nice feature, I had nothing to do with it. It shows the text of all "header" elements in the Markdown formatted README file. 

It's not super obvious, just click on the little icon with dots and lines next to where it says "README.md". 

Something similar happens for wiki pages, and a lot of that stuff will probably eventually move to wiki pages at some point. If I have the time and energy.

**Comment by jonbestdev** [comment]
![](https://media.giphy.com/media/12luQDyqvum5l6/giphy.gif)

**Comment by RedBearAK** [comment]
Closing as resolved.
