### ISSUE TITLE
Shift click for multiselect is slow to respond

### ISSUE THREAD

**Issue by CubeOfCheese** [RedBearAK/toshy#360]
```
Bare metal or virtual machine: 
(If in VM, which VM software): None

(Try running 'toshy-env' in a terminal to fill out the following fields...)
(EV) Toshy env module sees this environment:
		 DISTRO_ID       = 'fedora'
		 DISTRO_VER      = '40'
		 VARIANT_ID      = 'kde'
		 SESSION_TYPE    = 'wayland'
		 DESKTOP_ENV     = 'gnome'
		 DE_MAJ_VER      = '46'

Keyboard type (IBM, Chromebook, Windows, Apple): 
Keyboard device name (try 'toshy-devices'): 
```

* * *

Problem observed:
When I try to hold shift and click to select multiple things (tabs, files, etc) I have to try multiple times because it takes about a second for it to recognize that I am trying to do a shift click. I don't know how toshy works under the hood so I don't know how this could be improved, but 1 second is a noticeable delay and if it could be improved that would be great. If not, it's not a deal breaker, just a hiccup.

**Comment by RedBearAK** [comment]
@CubeOfCheese 

See this FAQ entry about the `suspend` timeout (and the next FAQ entry after it). 

https://github.com/RedBearAK/toshy/wiki/FAQ-(Frequently-Asked-Questions)#modclicking-blocked-by-keymapper-suspend-timeout

This is the most common setting that needs to be adjusted in the config file. By default there is a 1-second delay on modifier keys being held alone (without pressing another key).

**Comment by CubeOfCheese** [comment]
Wow that fixed it. Thanks so much!

**Comment by RedBearAK** [comment]
Excellent. 👍🏽 

Closing as resolved.
