### ISSUE TITLE
[BUG] Open Config Folder menu option does nothing

### ISSUE THREAD

**Issue by TheCleric** [RedBearAK/toshy#381]
```
Bare metal or virtual machine: bare metal

(Try running 'toshy-env' in a terminal to fill out the following fields...)

Linux distro name: pop
Distro version: 22.04
Distro variant: notfound
X11/Xorg or Wayland: x11
Desktop environment(s): unity
DE version(s): no_logic_for_DE

Keyboard type (IBM, Chromebook, Windows, Apple): Apple
Keyboard device name (try 'toshy-devices'): Keychron K8 Keychron K8
```

* * *

Problem observed:
When clicking the menu option for "Open Config Folder" from the task bar icon menu, nothing happens.

I watched through the `toshy-services-log` while doing this and saw nothing indicating an issue.

**Comment by RedBearAK** [comment]
@TheCleric 

This relies on the `xdg-open` command, and some kind of file manager must be associated with the “inode/directory” file type for it to do anything. You can use `xdg-mime` to check if anything is set as the default handler for that file type. 

Try running the command manually in the terminal. Normally this would open the path in your chosen file manager. 

```
xdg-open ~/.config/toshy
```

**Comment by TheCleric** [comment]
Ahh thanks for pointing me in the right direction @RedBearAK . It is indeed an `xdg-open` issue. Sorry for the confusion.

For anyone coming after me with this issue:

When running the `xdg-open ~/.config/toshy` command in a terminal I saw some weird errors such as:
```
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
WSL Interopability is disabled. Please enable it before using WSL.
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
[error] WSL Interoperability is disabled. Please enable it before using WSL.
/usr/bin/wslview: line 216: /mnt/c/Windows/System32/reg.exe: No such file or directory
```

I'm not running in WSL (am using a native linux install), so this was confusing. After some searching this behavior gets enabled if the `wslu` package is installed, so I had to run `sudo apt remove wslu`.

Once that was done, the command (and the menu option) worked as expected.
