### ISSUE TITLE
[BUG] Using an Apple keyboard alt/option and command are swapped

### ISSUE THREAD

**Issue by alexmarder** [RedBearAK/toshy#4]
Bare metal or virtual machine: bare metal
If VM, which VM software: 
Linux distro name: Fedora
Distro version: 38
Desktop environment(s): KDE

Problem observed: (try to include all relevant details)
* * *
Everything seems to work, except the alt/option key and command key is swapped; i.e., alt/option is the modifier for shortcuts.

**Comment by RedBearAK** [comment]
This is supposed to be automatic, but the process is a bit simplistic at this point. 

Can you follow the instructions in the FAQ entry and let me know if you can get it working by adding the device name to the correct list in the config file? 

https://github.com/RedBearAK/toshy#my-keyboard-is-not-recognized-as-the-correct-type

Gotta come up with a simpler way to deal with this. If you're successful let me know what the device name is and which type list you had to add it to, so I can include it in the default config.

**Comment by alexmarder** [comment]
My bad. The keyboard was not configured right. Sorry for the confusion.
