### ISSUE TITLE
(Question) Ubuntu how to add Super Left/Right to move windows?

### ISSUE THREAD

**Issue by dready** [RedBearAK/toshy#409]
First thanks for all the hard work. I have been using kinto until last ubuntu upgrade and decided to switch to toshy instead.

Unfortunately i am not fully understanding how the config works and how to interpret it. I was readying through all the issues my search matched and tried to get a hang of what's happening, but i am not...

What i am intended to figure out is how to add the hotkey Ctrl + Cursor Left/Right (on the keyboard) to move the active window on screen to the left or right side of the screen.

Ubuntu has a Shortcut for it called `View split on left/right`, but toshy is always disabling the hotkey on load.
![Screenshot from 2024-09-30 08-52-47](https://github.com/user-attachments/assets/44b4cb7f-25e4-4811-b2db-9f8321772cbc)

I was unable to figure out how to stop toshy from overriding it or how to override it from toshy so i can use the window hotkeys again.

Thanks in advance!

**Comment by RedBearAK** [comment]
@dready 

Toshy doesn't disable any GNOME shortcuts, other than the `overlay-key` Super key shortcut, which is disabled by the installer script. No native GNOME global shortcuts should be getting "disabled" by just loading the keymapper configuration, either manually or through the Toshy services. 

So I am a little confused about the description here. 

Tiling shortcuts in general are relatively difficult to get working reliably on different Linux desktop environments without having a shortcut collision with something that already exists. Unless you pick shortcuts that use multiple modifiers, like in issue #408. 

And one thing to understand about using the physical Ctrl key in a simple Ctrl+Left/Right kind of shortcut is that physical Ctrl is logically the Super key after a modmap is applied by the config, but then when you are in a "terminal" app that key reverts to being `LEFT_CTRL`. So if the native shortcuts are set to Super+Left/Right they should work in any app besides a terminal app, and terminal apps would need an override for `LC-Left` and `LC-Right` to convert them back into `Super-Left` and `Super-Right`. 

If that's all you're looking for we can probably get it working. But we have to figure out why you think Toshy is "disabling" the shortcuts in the screenshot. That part doesn't make any sense. 

If you click the "Delete" icon next to the disabled shortcuts, they should revert to their default state. Don't they normally use Super+Left/Right? 

I mostly use Plasma these days so I can't check the shortcuts at the moment.

**Comment by dready** [comment]
@RedBearAK Thanks for the fast response. I already clicked on the delete icon, but every time i relogin, even after screen lock it is reverted to another state.

Initially i just thought it's part of toshy but thanks to your explanation something else is responsible so i will dig in more and look who it is. I hope if i find the culprit no additional adjustment is necessary since then the default should work fine.

Many thanks!

**Comment by RedBearAK** [comment]
Do you have any kind of shell extension installed that does anything related to window management or tiling? Something like that could be trying to take over those shortcuts whenever you log in or unlock the screen. 

That’s the only thing I can think of that could be doing that.

**Comment by dready** [comment]
Many Thanks for your additional input.. i finally figured out who is responsible...

ubuntu now has a `Ubuntu Tiling Assistant` as a default System Extension and that overrides the Hotkeys from settings:
https://launchpad.net/ubuntu/+source/gnome-shell-extension-tiling-assistant

what i did not know, even when you disable all Extensions on the top, they still run.
![Screenshot from 2024-10-02 11-16-57](https://github.com/user-attachments/assets/34a447de-28ae-4bad-9699-dd0a3a5bfd21)

I thought if i disable all at once i can see if any extension is responsible, but no.. it still runs.

So many thanks for your help!!
