### ISSUE TITLE
(Question) What happens to shift-mouse click?

### ISSUE THREAD

**Issue by learex** [RedBearAK/toshy#410]
On Ubuntu 24.04, the shortcuts all seem to be working, but interestingly shift-left mouse does not select text. Is this intended?

**Comment by RedBearAK** [comment]
@learex 

See if this answers the question and takes care of the problem. This is the most common setting that needs to be tweaked in the config file. 

https://github.com/RedBearAK/toshy/wiki/FAQ-(Frequently-Asked-Questions)#modclicking-blocked-by-keymapper-suspend-timeout

**Comment by learex** [comment]
I seem to have missed that part in the FAQ. 😬
RTFMM(ore)C(losely) for me next time. Thanks!
