### ISSUE TITLE
(Question) On my AZERTY, CMD+A close the app

### ISSUE THREAD

**Issue by sbotte-consoneo** [RedBearAK/toshy#411]
When I do a CMD + A, it close the app. I read that it's the mapping that is based on a QWERTY keyboard. Where is it so I can edit it to work with my keyboard ?

**Comment by RedBearAK** [comment]
@sbotte-consoneo 

It will depend on your Python version, but it is something like this. 

```
cd ~/.config/toshy/.venv/lib/python3.11/site-packages/keyszer/models/
cp key.py key.py.original
xdg-open key.py
```

Might be a few hours before I can respond again.
