### ISSUE TITLE
(Question) Chevrons are inversed with @ and #

### ISSUE THREAD

**Issue by sbotte-consoneo** [RedBearAK/toshy#412]
Any ideas why <> key is inversed with @# key ?
I use a magic keyboard.

**Comment by RedBearAK** [comment]
@sbotte-consoneo 

What kind of keyboard layout/language is it? Other than "AZERTY"?

**Comment by sbotte-consoneo** [comment]
I use french macintosh layout on an Ubuntu 24. I don't know if this what you want to know.

**Comment by RedBearAK** [comment]
Are you saying that the `<>` symbols come out when you use the key just below the Escape key, and `@#` come out when you use the 102nd key that actually has the `<>` symbols on the key next to the left Shift key? 

I don't know why that would be happening. Does it happen only when Toshy is enabled, or both when Toshy is disabled and enabled? 

You can check the events coming from those keys with `evtest` in the terminal, and then we can see if the keymapper can fix the issue somehow.

**Comment by sbotte-consoneo** [comment]
You describe perfectly my probleme. 
And yes, It does the same thing with toshy disabled. 
I feel stupid to not have tested this without toshy.  
It more a linux issue. I'm going to find a solution linux side

**Comment by RedBearAK** [comment]
> I'm going to find a solution linux side.

If you can't find a good solution for what's happening, the keymapper can probably help out. There was another user who felt the need to swap those two keys on an English ISO international keyboard layout. 

See this issue thread: https://github.com/RedBearAK/toshy/issues/359
