### ISSUE TITLE
(Enh) Install on Tuxedo OS without override (DONE)

### ISSUE THREAD

**Issue by RedBearAK** [RedBearAK/toshy#42]
@alexmarder 

Merged a change into the main branch to support installing on Tuxedo OS (a variant of Ubuntu 22.04 LTS) without needing to use `--override-distro`.

**Comment by alexmarder-mach** [comment]
Thank you! This is an incredible project!

**Comment by alexmarder** [comment]
Thank you! This is an incredible project!

**Comment by RedBearAK** [comment]
> Thank you! This is an incredible project!

@alexmarder 

Thanks for the kind words! 👍
