### ISSUE TITLE
(Question) Where is located right alt / alt gr to print alternative chars like @?

### ISSUE THREAD

**Issue by alvarokrn** [RedBearAK/toshy#423]
I'm used to press right alt on Mac or Alt Gr to print special characters like @ or currency symbol like euro and dollars. Now I can not, where is this key located?

**Comment by RedBearAK** [comment]
@alvarokrn 

Try the preferences submenu in the tray icon menu. There is an option for letting Alt_Gr work like it should, for international keyboard users. No need to restart the keymapper service. 

After that it might depend on your keyboard layout settings. And you may need to edit the key definition file for certain characters and shortcuts to work as expected. 

Let me know how it goes and what layout you use.

**Comment by alvarokrn** [comment]
It worked! Thanks!
