### ISSUE TITLE
(Question) UK keyboard mapping

### ISSUE THREAD

**Issue by dmgeurts** [RedBearAK/toshy#429]
Thank you for Toshy, it looks pretty promising, but I'm struggling to get the keys right for a UK keyboard.

I've also noticed that cmd-a is options-a so would like to change this to cmd-. And how could I remap ~± and `§. The specific UK element is shift-3 being '#' instead of '£', so I'd like to swap shift-3 and cmd-3 to be option-3 and shift-3 respectively.

**Comment by RedBearAK** [comment]
@dmgeurts 

There should be some clues about fixing the layout in this issue. 

https://github.com/RedBearAK/toshy/issues/359

I’m away from my computer for a few more days, so my answers may not be as verbose as you might see in other issue threads.

**Comment by dmgeurts** [comment]
@RedBearAK 

Thank you, mapping Grave and 102ND fixed the main thing:

```
# Suggested location for adding custom modmaps for personal use.
###################################################################################################
###  SLICE_MARK_START: user_custom_modmaps  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE

modmap("Cond modmap - User overrides",{
    # Swap Grave and KEY_102ND keys identities
    Key.KEY_102ND:              Key.GRAVE,
    Key.GRAVE:                  Key.KEY_102ND,
}, when = lambda ctx:
    cnfg.screen_has_focus and
    matchProps(not_clas=remoteStr)(ctx)
)

###  SLICE_MARK_END: user_custom_modmaps  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

The following worked for swapping `£` and `#`: 

```
###################################################################################################
###  SLICE_MARK_START: user_apps  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE


keymap("User hardware keys", {
    # PUT UNIVERSAL REMAPS FOR HARDWARE KEYS HERE
    # KEYMAP WILL BE ACTIVE IN ALL DESKTOP ENVIRONMENTS/DISTROS
    C("RC-KEY_3"):                   C("Shift-KEY_3"),             # In-app switching (#)
    C("Shift-KEY_3"):                C("RA-KEY_3"),                # In-app switching (£)

}, when = lambda ctx:
    cnfg.screen_has_focus and
    matchProps(not_clas=remoteStr)(ctx)
)

###  SLICE_MARK_END: user_apps  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

For some reason the macOS default of cmd-c and cmd-v is opt-c and opt-v in Toshy, is there a reason for this?

**Comment by RedBearAK** [comment]
> For some reason the macOS default of cmd-c and cmd-v is opt-c and opt-v in Toshy, is there a reason for this?

Depending on the keyboard device the type may be misidentified. Check this FAQ entry: 

https://github.com/RedBearAK/toshy/wiki/FAQ-(Frequently-Asked-Questions)#my-keyboard-is-not-recognized-as-the-correct-type

You may need to change the remaps in the keymap (not the modmap) after fixing the keyboard type. 

Describe the keyboard device and the name it presents in `toshy-devices`.

**Comment by RedBearAK** [comment]
> Setting the keyboard type manually to Apple or Windows does not swap the cmd and option keys for copy/paste.

If only those specific shortcuts are affected, maybe Parallels is intercepting those key combos somehow. Normally changing the type would swap the Option/Command positions. 

You might need to change something in the VM settings, or tell the guest OS the keyboard is an Apple keyboard. I’m not sure how to do that in GNOME. 

When I use VMs on a Linux host the normal keyboard device is detected in the VM, but it sounds like the Parallels virtual keyboard is doing something a bit different.

**Comment by dmgeurts** [comment]
Indeed, Parallels already has the mapping for copy/paste built in, which without Toshy works perfectly to map cmd-c and cmd-v to Ctrl-C and Ctrl-V. How would I disable the mapping in Toshy so that the Parallels mapping is reinstated?

**Comment by RedBearAK** [comment]
You might be able to just start adding remaps for specific combos into the same custom keymap you used earlier. But many common global shortcuts like Z/X/C/V/A/S/F/Q/W aren’t in the config file at all, they just automatically work once the Command key becomes Right Control via modmapping. 

I’m still not entirely sure why the changing of the keyboard type had no effect. It would be good to check the verbose output from `toshy-debug` to see what the keymapper sees when pressing Option, Command, and the various combos, and what happens after changing the keyboard type.

**Comment by dmgeurts** [comment]
`toshy-debug` output

For Left-option and Left-command keys:

```
(II) in LEFT_ALT (press)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) KBTYPE: 'Windows' | (CACHED) Default type for dev: 'Parallels Virtual Keyboard'
(DD) MODMAP: LEFT_ALT => RIGHT_CTRL [Cond modmap - Terms - Win kbd]
(DD) on_key RIGHT_CTRL press
(DD) suspending keys: [VCmd<Key.RIGHT_CTRL>]

(II) in LEFT_ALT (release)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) on_key RIGHT_CTRL release
(DD) resume because of mod release
(DD) resuming keys: [<Key.RIGHT_CTRL: 97>]
(OO) press RIGHT_CTRL 1730335110.5018952
(OO) release RIGHT_CTRL 1730335110.5019794

(II) in LEFT_META (press)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) KBTYPE: 'Windows' | (CACHED) Default type for dev: 'Parallels Virtual Keyboard'
(DD) MODMAP: LEFT_META => LEFT_ALT [Cond modmap - Terms - Win kbd]
(DD) on_key LEFT_ALT press
(DD) suspending keys: [VLOpt<Key.LEFT_ALT>]

(II) in LEFT_META (release)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) on_key LEFT_ALT release
(DD) resume because of mod release
(DD) resuming keys: [<Key.LEFT_ALT: 56>]
(OO) press LEFT_ALT 1730335117.1931543
(OO) release LEFT_ALT 1730335117.1932147
```

for Option-C:

```
(II) in LEFT_ALT (press)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) KBTYPE: 'Windows' | (CACHED) Default type for dev: 'Parallels Virtual Keyboard'
(DD) MODMAP: LEFT_ALT => RIGHT_CTRL [Cond modmap - Terms - Win kbd]
(DD) on_key RIGHT_CTRL press
(DD) suspending keys: [VCmd<Key.RIGHT_CTRL>]

(II) in C (press)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) on_key C press
(DD) KBTYPE: 'Windows' | (CACHED) Default type for dev: 'Parallels Virtual Keyboard'

(DD) WM_CLASS: 'gnome-terminal-server' | WM_NAME: 'user@vm: ~'
(DD) DEVICE: 'Parallels Virtual Keyboard' | CAPS_LOCK: 'False' | NUM_LOCK: 'False'
(DD) ACTIVE KEYMAPS:
     'User hardware keys', 'Wordwise - not vscode', 'GenTerms overrides:
      … Ubuntu/Fedora', 'GenTerms overrides: GNOME', 'General Terminals', 'GenGUI
      … overrides: not Chromebook', 'GenGUI overrides: Ubuntu', 'GenGUI overrides:
      … GNOME', 'General GUI', 'Diagnostics'
(DD) COMBO: VCmd-C => Ctrl-Shift-C in KMAP: 'General Terminals'
(DD) spent modifiers [<Key.RIGHT_CTRL: 97>]
(DD) resuspending keys
(DD) suspending keys: [VCmd<Key.RIGHT_CTRL>]
(OO) press LEFT_CTRL 1730335447.955813
(OO) press LEFT_SHIFT 1730335447.9868207
(OO) press C 1730335448.0188534
(OO) release C 1730335448.0252857
(OO) release LEFT_SHIFT 1730335448.0584924
(OO) release LEFT_CTRL 1730335448.0894985

(II) in C (release)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) on_key C release

(II) in LEFT_ALT (release)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) on_key RIGHT_CTRL release
(DD) silent lift of spent mod RIGHT_CTRL
```

For command-C:

```
(II) in LEFT_CTRL (press)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) KBTYPE: 'Windows' | (CACHED) Default type for dev: 'Parallels Virtual Keyboard'
(DD) MODMAP: LEFT_CTRL => LEFT_CTRL [Cond modmap - Terms - Win kbd]
(DD) on_key LEFT_CTRL press
(DD) suspending keys: [VLCtrl<Key.LEFT_CTRL>]

(II) in C (press)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) on_key C press
(DD) KBTYPE: 'Windows' | (CACHED) Default type for dev: 'Parallels Virtual Keyboard'
(DD) resuming keys: [<Key.LEFT_CTRL: 29>]
(OO) press LEFT_CTRL 1730335271.2438202
(OO) press C 1730335271.243868

(II) in C (release)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) on_key C release
(OO) release C 1730335271.2445724

(II) in LEFT_CTRL (release)
(CX) SHELL_EXT: Using UUID 'xremap@k0kubun.com' for window context
(DD) on_key LEFT_CTRL release
(DD) resume because of mod release
(OO) release LEFT_CTRL 1730335271.2452219
^Csignal INT received
(-K) Ungrabbing: 'Parallels Virtual Keyboard' (removed)
```

If I force the keyboard type to Apple, the option and command keys are swapped, but ctrl-c is issued instead of copy.

**Comment by RedBearAK** [comment]
So the fundamental problem is that Parallels is trying to do a simplistic version of what Toshy’s config does. But it remaps the Command key to be LEFT_CTRL instead of RIGHT_CTRL. That’s what messes things up. And that would be problematic to re-remap. You need LEFT_CTRL for terminal stuff. 

In the preferences for Parallels you should be able to start disabling those remaps of macOS shortcuts for that specific VM, theoretically letting the keymapper see the correct key combos to remap. If that works out then it should simply be a matter of changing the keyboard type to Apple to get Option and Command in the right place. With the Parallels remaps disabled, the Parallels virtual keyboard should just start passing through the real key codes, and it should act entirely like the raw MBP keyboard. I hope.

**Comment by dmgeurts** [comment]
Interesting, turning off the mappings in Parallels and manually setting the keyboard type to Apple, fixed the last issue. Thank you!
