### ISSUE TITLE
[BUG] Not starting on Fedora 41 / KDE Plasma

### ISSUE THREAD

**Issue by brownphotographic** [RedBearAK/toshy#432]
Toshy will not start after upgrading from Fedora 40 to 41

```
Bare metal

(Try running 'toshy-env' in a terminal to fill out the following fields...)

 DISTRO_ID       = 'fedora'
 DISTRO_VER      = '41'
 VARIANT_ID      = 'workstation'
 SESSION_TYPE    = 'wayland'
 DESKTOP_ENV     = 'kde'
 DE_MAJ_VER      = '6'



Keyboard type Apple: 
Keyboard device name Keychron K1
```

* * *

Problem observed:
Toshy will not start after upgrading from Fedora 40 to 41. DE is KDE Plasma . Status message below

Interestingly when I run toshy-devices I get this error

```
toshy-devices

List of devices seen by the keymapper (xwaykeyz or keyszer): 

Traceback (most recent call last):
  File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
    from xwaykeyz.cli import main
ModuleNotFoundError: No module named 'xwaykeyz'

```

```
rbrown@fedora:~$ toshy-services-status

Current status of Toshy systemd services...
--------------------------------------------------------------------------------
× toshy-cosmic-dbus.service - Toshy COSMIC D-Bus Service
     Loaded: loaded (/home/rbrown/.config/systemd/user/toshy-cosmic-dbus.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Sun 2024-11-03 06:44:54 EST; 28min ago
   Duration: 1.143s
 Invocation: caf89e1a55cc40f59e67c75a62e0bcb5
    Process: 2985 ExecStartPre=/bin/bash -c if [ -z "$XDG_SESSION_TYPE" ]; then sleep 3; exit 1; fi (code=exited, status=0/SUCCESS)
    Process: 2989 ExecStart=/bin/bash -c env TERM=xterm $HOME/.config/toshy/scripts/bin/toshy-cosmic-dbus-service.sh (code=exited, status=1/FAILURE)
   Main PID: 2989 (code=exited, status=1/FAILURE)

Nov 03 06:44:54 fedora systemd[1543]: toshy-cosmic-dbus.service: Scheduled restart job, restart counter is at 6.
Nov 03 06:44:54 fedora systemd[1543]: toshy-cosmic-dbus.service: Start request repeated too quickly.
Nov 03 06:44:54 fedora systemd[1543]: toshy-cosmic-dbus.service: Failed with result 'exit-code'.
Nov 03 06:44:54 fedora systemd[1543]: Failed to start toshy-cosmic-dbus.service - Toshy COSMIC D-Bus Service.
--------------------------------------------------------------------------------
× toshy-kde-dbus.service - Toshy KDE D-Bus Service
     Loaded: loaded (/home/rbrown/.config/systemd/user/toshy-kde-dbus.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Sun 2024-11-03 06:44:54 EST; 28min ago
   Duration: 1.143s
 Invocation: d6e80e9728b442868cb11a03ea70d882
    Process: 2986 ExecStartPre=/bin/bash -c if [ -z "$XDG_SESSION_TYPE" ]; then sleep 3; exit 1; fi (code=exited, status=0/SUCCESS)
    Process: 2992 ExecStart=/bin/bash -c env TERM=xterm $HOME/.config/toshy/scripts/bin/toshy-kde-dbus-service.sh (code=exited, status=1/FAILURE)
   Main PID: 2992 (code=exited, status=1/FAILURE)

Nov 03 06:44:54 fedora systemd[1543]: toshy-kde-dbus.service: Scheduled restart job, restart counter is at 6.
Nov 03 06:44:54 fedora systemd[1543]: toshy-kde-dbus.service: Start request repeated too quickly.
Nov 03 06:44:54 fedora systemd[1543]: toshy-kde-dbus.service: Failed with result 'exit-code'.
Nov 03 06:44:54 fedora systemd[1543]: Failed to start toshy-kde-dbus.service - Toshy KDE D-Bus Service.
--------------------------------------------------------------------------------
× toshy-wlroots-dbus.service - Toshy Wlroots D-Bus Service
     Loaded: loaded (/home/rbrown/.config/systemd/user/toshy-wlroots-dbus.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Sun 2024-11-03 06:44:54 EST; 28min ago
   Duration: 1.142s
 Invocation: baf6fe9d7ef943d6b3688fe2cabf18f9
    Process: 2987 ExecStartPre=/bin/bash -c if [ -z "$XDG_SESSION_TYPE" ]; then sleep 3; exit 1; fi (code=exited, status=0/SUCCESS)
    Process: 2993 ExecStart=/bin/bash -c env TERM=xterm $HOME/.config/toshy/scripts/bin/toshy-wlroots-dbus-service.sh (code=exited, status=1/FAILURE)
   Main PID: 2993 (code=exited, status=1/FAILURE)

Nov 03 06:44:54 fedora systemd[1543]: toshy-wlroots-dbus.service: Scheduled restart job, restart counter is at 6.
Nov 03 06:44:54 fedora systemd[1543]: toshy-wlroots-dbus.service: Start request repeated too quickly.
Nov 03 06:44:54 fedora systemd[1543]: toshy-wlroots-dbus.service: Failed with result 'exit-code'.
Nov 03 06:44:54 fedora systemd[1543]: Failed to start toshy-wlroots-dbus.service - Toshy Wlroots D-Bus Service.
--------------------------------------------------------------------------------
● toshy-session-monitor.service - Toshy Session Monitor
     Loaded: loaded (/home/rbrown/.config/systemd/user/toshy-session-monitor.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Sun 2024-11-03 06:44:18 EST; 29min ago
 Invocation: 48c8bb8e327d475cb07507710ca9d99f
   Main PID: 2005 (bash)
      Tasks: 2 (limit: 77012)
     Memory: 1.3M (peak: 5M)
        CPU: 43.393s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/toshy-session-monitor.service
             ├─ 2005 bash /home/rbrown/.config/toshy/scripts/toshy-service-session-monitor.sh
             └─19550 sleep 2

Nov 03 06:44:18 fedora systemd[1543]: Started toshy-session-monitor.service - Toshy Session Monitor.
--------------------------------------------------------------------------------
● toshy-config.service - Toshy Config Service
     Loaded: loaded (/home/rbrown/.config/systemd/user/toshy-config.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: activating (auto-restart) (Result: exit-code) since Sun 2024-11-03 07:13:40 EST; 3s ago
 Invocation: e6265e3bfd804c4385c8bfc57532cb5b
    Process: 19520 ExecStartPre=/bin/bash -c env TERM=xterm $HOME/.config/toshy/scripts/toshy-service-config-execstartpre.sh (code=exited, status=0/SUCCESS)
    Process: 19531 ExecStart=/bin/bash -c env TERM=xterm $HOME/.config/toshy/scripts/toshy-service-config.sh (code=exited, status=1/FAILURE)
   Main PID: 19531 (code=exited, status=1/FAILURE)
   Mem peak: 6.6M
        CPU: 259ms
--------------------------------------------------------------------------------
Use 'toshy-services-disable' to disable Toshy services autostart at login.
Use 'toshy-services-enable' to (re)enable Toshy services autostart at login.
Use 'toshy-systemd-remove' to uninstall/remove Toshy services.
Use 'toshy-systemd-setup' to install/reinstall Toshy services.


```

**Comment by RedBearAK** [comment]
@brownphotographic 

Simple answer is probably to reinstall Toshy. I’m not sure what the actual problem is without more testing, but reinstalling should fix it. 

Your config customizations and preferences should be carried over. 

Some output from `toshy-services-log` and `toshy-debug` before you reinstall could help me prevent this. Maybe.

**Comment by brownphotographic** [comment]
Hi, thanks for the response!

I tried uninstall and reinstall with toshy-systemd-setup. It looks like the error is to do with xwaykeyz . I have pasted the output of the reinstall, debug and log files

Thank you!

```
rbrown@fedora:~$ toshy-systemd-setup

Setting up Toshy service unit files in '/home/rbrown/.config/systemd/user'...

Removing Toshy systemd services...

Removed '/home/rbrown/.config/systemd/user/default.target.wants/toshy-cosmic-dbus.service'.
Removed '/home/rbrown/.config/systemd/user/default.target.wants/toshy-kde-dbus.service'.
Removed '/home/rbrown/.config/systemd/user/default.target.wants/toshy-wlroots-dbus.service'.
Removed '/home/rbrown/.config/systemd/user/default.target.wants/toshy-config.service'.
Removed '/home/rbrown/.config/systemd/user/default.target.wants/toshy-session-monitor.service'.

Finished removing Toshy systemd services.


Issuing systemctl daemon-reload...

Starting Toshy systemd services...
Created symlink '/home/rbrown/.config/systemd/user/default.target.wants/toshy-cosmic-dbus.service' → '/home/rbrown/.config/systemd/user/toshy-cosmic-dbus.service'.
Created symlink '/home/rbrown/.config/systemd/user/default.target.wants/toshy-kde-dbus.service' → '/home/rbrown/.config/systemd/user/toshy-kde-dbus.service'.
Created symlink '/home/rbrown/.config/systemd/user/default.target.wants/toshy-wlroots-dbus.service' → '/home/rbrown/.config/systemd/user/toshy-wlroots-dbus.service'.
Created symlink '/home/rbrown/.config/systemd/user/default.target.wants/toshy-config.service' → '/home/rbrown/.config/systemd/user/toshy-config.service'.
Created symlink '/home/rbrown/.config/systemd/user/default.target.wants/toshy-session-monitor.service' → '/home/rbrown/.config/systemd/user/toshy-session-monitor.service'.

Displaying status of Toshy systemd services...

● toshy-cosmic-dbus.service - Toshy COSMIC D-Bus Service
     Loaded: loaded (/home/rbrown/.config/systemd/user/toshy-cosmic-dbus.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: activating (auto-restart) (Result: exit-code) since Sun 2024-11-03 20:57:00 EST; 3s ago
 Invocation: dc5a1c90a13f45ecb0b698768f113818
   Main PID: 56671 (code=exited, status=1/FAILURE)
   Mem peak: 5.7M
        CPU: 156ms

● toshy-kde-dbus.service - Toshy KDE D-Bus Service
     Loaded: loaded (/home/rbrown/.config/systemd/user/toshy-kde-dbus.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: activating (auto-restart) (Result: exit-code) since Sun 2024-11-03 20:57:01 EST; 3s ago
 Invocation: 00763a175d0c42dc95ce50103d0a8c98
   Main PID: 56691 (code=exited, status=1/FAILURE)
   Mem peak: 12.1M
        CPU: 197ms

● toshy-wlroots-dbus.service - Toshy Wlroots D-Bus Service
     Loaded: loaded (/home/rbrown/.config/systemd/user/toshy-wlroots-dbus.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: activating (auto-restart) (Result: exit-code) since Sun 2024-11-03 20:57:02 EST; 2s ago
 Invocation: 9c7aa5f0f0d14d07b31f40d549a54383
   Main PID: 56713 (code=exited, status=1/FAILURE)
   Mem peak: 5.8M
        CPU: 143ms

● toshy-session-monitor.service - Toshy Session Monitor
     Loaded: loaded (/home/rbrown/.config/systemd/user/toshy-session-monitor.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Sun 2024-11-03 20:57:03 EST; 2s ago
 Invocation: 5988ba5603ac440ba47a4dbb6c1fe4e3
   Main PID: 56762 (bash)
      Tasks: 2 (limit: 77012)
     Memory: 912K (peak: 3M)
        CPU: 38ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/toshy-session-monitor.service
             ├─56762 bash /home/rbrown/.config/toshy/scripts/toshy-service-session-monitor.sh
             └─56805 sleep 2

Nov 03 20:57:03 fedora systemd[1521]: Started toshy-session-monitor.service - Toshy Session Monitor.

● toshy-config.service - Toshy Config Service
     Loaded: loaded (/home/rbrown/.config/systemd/user/toshy-config.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: activating (auto-restart) (Result: exit-code) since Sun 2024-11-03 20:57:02 EST; 3s ago
 Invocation: 899db37f9be04f1a87399c6f722e1dba
   Main PID: 56736 (code=exited, status=1/FAILURE)
   Mem peak: 5.9M
        CPU: 297ms

Finished installing Toshy systemd services...

HINT: In X11, tap a modifier key before trying shortcuts.

rbrown@fedora:~$ toshy-debug
Stopping Toshy systemd services...
Toshy systemd services stopped.
Traceback (most recent call last):
  File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
    from xwaykeyz.cli import main
ModuleNotFoundError: No module named 'xwaykeyz'
```


debug:
```
rbrown@fedora:~$ toshy-debug
Stopping Toshy systemd services...
Toshy systemd services stopped.
Traceback (most recent call last):
  File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
    from xwaykeyz.cli import main
ModuleNotFoundError: No module named 'xwaykeyz'
```


log:
Showing systemd journal messages for Toshy services (since last boot):
Nov 03 20:53:23 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:53:28 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1050.
Nov 03 20:53:28 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:53:28 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:53:28 fedora bash[55195]: Traceback (most recent call last):
Nov 03 20:53:28 fedora bash[55195]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:53:28 fedora bash[55195]:     from xwaykeyz.cli import main
Nov 03 20:53:28 fedora bash[55195]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:53:28 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:53:28 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:53:33 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1051.
Nov 03 20:53:33 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:53:33 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:53:34 fedora bash[55255]: Traceback (most recent call last):
Nov 03 20:53:34 fedora bash[55255]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:53:34 fedora bash[55255]:     from xwaykeyz.cli import main
Nov 03 20:53:34 fedora bash[55255]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:53:34 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:53:34 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:53:39 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1052.
Nov 03 20:53:39 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:53:39 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:53:39 fedora bash[55312]: Traceback (most recent call last):
Nov 03 20:53:39 fedora bash[55312]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:53:39 fedora bash[55312]:     from xwaykeyz.cli import main
Nov 03 20:53:39 fedora bash[55312]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:53:39 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:53:39 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:53:44 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1053.
Nov 03 20:53:44 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:53:44 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:53:45 fedora bash[55344]: Traceback (most recent call last):
Nov 03 20:53:45 fedora bash[55344]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:53:45 fedora bash[55344]:     from xwaykeyz.cli import main
Nov 03 20:53:45 fedora bash[55344]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:53:45 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:53:45 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:53:50 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1054.
Nov 03 20:53:50 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:53:50 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:53:50 fedora bash[55401]: Traceback (most recent call last):
Nov 03 20:53:50 fedora bash[55401]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:53:50 fedora bash[55401]:     from xwaykeyz.cli import main
Nov 03 20:53:50 fedora bash[55401]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:53:50 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:53:50 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:53:55 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1055.
Nov 03 20:53:55 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:53:55 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:53:56 fedora bash[55460]: Traceback (most recent call last):
Nov 03 20:53:56 fedora bash[55460]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:53:56 fedora bash[55460]:     from xwaykeyz.cli import main
Nov 03 20:53:56 fedora bash[55460]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:53:56 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:53:56 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:54:01 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1056.
Nov 03 20:54:01 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:54:01 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:54:01 fedora bash[55505]: Traceback (most recent call last):
Nov 03 20:54:01 fedora bash[55505]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:54:01 fedora bash[55505]:     from xwaykeyz.cli import main
Nov 03 20:54:01 fedora bash[55505]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:54:01 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:54:01 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:54:06 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1057.
Nov 03 20:54:06 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:54:06 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:54:07 fedora bash[55550]: Traceback (most recent call last):
Nov 03 20:54:07 fedora bash[55550]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:54:07 fedora bash[55550]:     from xwaykeyz.cli import main
Nov 03 20:54:07 fedora bash[55550]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:54:07 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:54:07 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:54:12 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1058.
Nov 03 20:54:12 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:54:12 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:54:12 fedora bash[55599]: Traceback (most recent call last):
Nov 03 20:54:12 fedora bash[55599]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:54:12 fedora bash[55599]:     from xwaykeyz.cli import main
Nov 03 20:54:12 fedora bash[55599]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:54:12 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:54:12 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:54:17 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1059.
Nov 03 20:54:17 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:54:17 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:54:18 fedora bash[55637]: Traceback (most recent call last):
Nov 03 20:54:18 fedora bash[55637]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:54:18 fedora bash[55637]:     from xwaykeyz.cli import main
Nov 03 20:54:18 fedora bash[55637]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:54:18 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:54:18 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:54:23 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1060.
Nov 03 20:54:23 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:54:23 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:54:23 fedora bash[55750]: Traceback (most recent call last):
Nov 03 20:54:23 fedora bash[55750]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:54:23 fedora bash[55750]:     from xwaykeyz.cli import main
Nov 03 20:54:23 fedora bash[55750]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:54:23 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:54:23 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:54:28 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1061.
Nov 03 20:54:28 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:54:28 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:54:29 fedora bash[55798]: Traceback (most recent call last):
Nov 03 20:54:29 fedora bash[55798]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:54:29 fedora bash[55798]:     from xwaykeyz.cli import main
Nov 03 20:54:29 fedora bash[55798]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:54:29 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:54:29 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:54:34 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1062.
Nov 03 20:54:34 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:54:34 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:54:34 fedora bash[55830]: Traceback (most recent call last):
Nov 03 20:54:34 fedora bash[55830]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:54:34 fedora bash[55830]:     from xwaykeyz.cli import main
Nov 03 20:54:34 fedora bash[55830]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:54:34 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:54:34 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:54:39 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart counter is at 1063.
Nov 03 20:54:39 fedora systemd[1521]: Starting toshy-config.service - Toshy Config Service...
Nov 03 20:54:39 fedora systemd[1521]: Started toshy-config.service - Toshy Config Service.
Nov 03 20:54:40 fedora bash[55872]: Traceback (most recent call last):
Nov 03 20:54:40 fedora bash[55872]:   File "/home/rbrown/.config/toshy/.venv/bin/xwaykeyz", line 5, in <module>
Nov 03 20:54:40 fedora bash[55872]:     from xwaykeyz.cli import main
Nov 03 20:54:40 fedora bash[55872]: ModuleNotFoundError: No module named 'xwaykeyz'
Nov 03 20:54:40 fedora systemd[1521]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:54:40 fedora systemd[1521]: toshy-config.service: Failed with result 'exit-code'.
Nov 03 20:54:45 fedora systemd[1521]: toshy-config.service: Scheduled restart job, restart count`

**Comment by RedBearAK** [comment]
> toshy-systemd-setup

That just reinstalls or installs the `systemd` unit files to make Toshy start up automatically when you log in. You need to reinstall using the original setup script or a newly downloaded zip file. The `setup_toshy.py` script. 

I think this happens whenever the main Python version on the host changes significantly from the Python version in the virtual environment (venv) folder. I've seen similar issues on more than one distro after a distribution upgrade. And Tumbleweed when they migrated the whole system from Python 3.10 to 3.11. I don't really understand why it causes this "Module not found" error. But reinstalling Toshy always seems to get it working again. 

Just grab a new zip and reinstall from that.

**Comment by brownphotographic** [comment]
Ah! Thank you

That worked. Uninstalled, the reinstalled with the setup.py script.

Thanks so much

**Comment by RedBearAK** [comment]
> That worked. 

Good. 

Shouldn't happen again until upgrading from F41 to F42. Meanwhile I'll keep looking into how to prevent the issue.

**Comment by RedBearAK** [comment]
@brownphotographic 

BTW, the "uninstall" part? Probably not necessary. Toshy does basically a clean refresh on every install, then restores you preferences and customizations of the config. Uninstalling is just meant for when you really want to remove everything. 

👍🏽
