### ISSUE TITLE
(Question) Edit shortcut?

### ISSUE THREAD

**Issue by goodeesh** [RedBearAK/toshy#438]
Hi there! Love the app! It works amazing on fedora 41 and I am really loving it!
I wanted to ask something though, where could I go to changue a little bit the configuration??
There is the extension in gnome called search light that give a lot of vibes from mac os spotlight search and I would prefer it rather than the super key for when I do alt+space
This was I would avoid the animation of showing the apps view for when I actually just want to search for something.

I would be very glad if someone can point me in the right direction here :)

Cheersand thanks again!

**Comment by RedBearAK** [comment]
@goodeesh 


See if this Wiki article helps you out with that. 

https://github.com/RedBearAK/toshy/wiki/How-to-(persistently)-change-the-Cmd-Space-remap

**Comment by goodeesh** [comment]
That article sounds amazing, exactly what I was looking for, thank you very much!!

**Comment by RedBearAK** [comment]
Edited the last comment to put triple Grave (backtick) characters around the code blocks, and added "py" for Python syntax highlighting. 

Nice work getting it working.
