### ISSUE TITLE
(Question) How to install Toshy on Fedora atomic distros

### ISSUE THREAD

**Issue by alexanderflink** [RedBearAK/toshy#439]
Hello!

New to Linux and Toshy. I'm running Fedora Sway Atomic. Since it's an immutable distro, `dnf` is not available by default. I have to enter a toolbox or use rpm-ostree to layer packages. It seems the toshy installer expects `dnf` to be available. I tried installing toshy in a toolbox, but it doesn't seem to function correctly, keymaps are not applied (I can provide debug info if needed).

Is using toolbox the correct way to set up Toshy on Fedora Atomic, or should the installer work without using it?

The installer identifies my system as
```
DISTRO_ID = 'fedora'
DISTRO_VER = '41'
VARIANT_ID = 'sway-atomic'
SESSION_TYPE = 'wayland'
DESKTOP_ENV = 'sway'
DE_MAJ_VER = 'no_logic_for_de'
WINDOW_MGR = 'sway'
```

But when I run `./setup_toshy.py install`, it errors with:
`(EE) Package manager command (dnf) not available. Unable to continue`

**Comment by RedBearAK** [comment]
@alexanderflink 

This should work: 

```
./setup_toshy.py install —override-distro silverblue
```

The atomic variants don’t do a great job identifying themselves differently from regular Fedora. But I might be able to use that variant ID for the Sway atomic variant in the future.

**Comment by RedBearAK** [comment]
I have never been able to figure out how to get Toshy working from a container, due to the device permissions required.

**Comment by alexanderflink** [comment]
That works! THANK YOU! I can finally use my linux machine comfortably. 🙂
