### ISSUE TITLE
[BUG] Toshy fails to autostart in Hyprland on Fedora Asahi Linux 40

### ISSUE THREAD

**Issue by patchedsoul** [RedBearAK/Toshy#442]
```
Bare metal or virtual machine: 
(If in VM, which VM software): None

(Try running 'toshy-env' in a terminal to fill out the following fields...)

Linux distro name: Asahi Linux
Distro version: 40
Distro variant: minimal
X11/Xorg or Wayland: Wayland
Desktop environment(s): Hyprland
DE version(s): 

Keyboard type (IBM, Chromebook, Windows, Apple): Macbook Pro
Keyboard device name (try 'toshy-devices'): Apple MTP keyboard
```

* * *

Problem observed:
upon clean install, toshy starts and works as intended. After a reboot, it fails to autostart:
```
Nov 16 08:22:20 fedora systemd[8407]: toshy-config.service: Failed with result 'exit-code'.
Nov 16 08:22:25 fedora systemd[8407]: toshy-config.service: Scheduled restart job, restart counter is at 10.
Nov 16 08:22:25 fedora systemd[8407]: Starting toshy-config.service - Toshy Config Service...
Nov 16 08:22:25 fedora systemd[8407]: Started toshy-config.service - Toshy Config Service.
Nov 16 08:22:27 fedora bash[9590]: Toshy Config Service: XDG_SESSION_TYPE not set. Restarting service.
Nov 16 08:22:27 fedora systemd[8407]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 08:22:27 fedora systemd[8407]: toshy-config.service: Failed with result 'exit-code'.
Nov 16 08:22:32 fedora systemd[8407]: toshy-config.service: Scheduled restart job, restart counter is at 11.
Nov 16 08:22:32 fedora systemd[8407]: Starting toshy-config.service - Toshy Config Service...
Nov 16 08:22:32 fedora systemd[8407]: Started toshy-config.service - Toshy Config Service.
Nov 16 08:22:34 fedora bash[9645]: Toshy Config Service: XDG_SESSION_TYPE not set. Restarting service.
Nov 16 08:22:34 fedora systemd[8407]: toshy-config.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 08:22:35 fedora systemd[8407]: toshy-config.service: Failed with result 'exit-code'.
```

I'm out of things to check/test and need some help :)

**Comment by RedBearAK** [comment]
@patchedsoul 

I think your primary issue here is just that you are running Hyprland, which is one of those things that's "just a window manager" and for some reason doesn't automatically process the items in the user's XDG autostart location, like most desktop environments do. Maybe this is primarily a defect of the JaKooLit setup script. 

The items in the XDG autostart location are necessary to open up the user's environment variables to the (also user) systemd units, that will start up the necessary components to identify the environment and prompt the keymapper to use the correct window context method. Also the tray icon gets launched from there. The services will just keep restarting until they can "see" your environment variables. 

I don't know if there's a more correct way to fix this, but I made a crude XDG autostart processor script specifically for this type of situation. If you call that script from your Hyprland config file, it should take care of the problem. Every window manager seems to have their own syntax for "launching" something from the config file at startup. You'll have to look up how to do that. I tested it in Hyprland once but that was months ago, and I don't recall exactly how I did it. 

The processor script is located at the path below, in the Toshy config folder. You can call it from that location or copy it to some other folder where you keep executable scripts and call it from there. It doesn't really have anything in particular to do with Toshy, it just processes the XDG autostart items in a generic way. Could be used with any window manager. 

```
~/.config/toshy/scripts/XDG-Autostart-processor.sh
```

Let me know if this doesn't solve the issue with autostarting Toshy in Hyprland.

**Comment by RedBearAK** [comment]
@patchedsoul 

BTW, this is unrelated to Toshy, but if you leave a Fedora install with the automatic default hostname of `fedora`, this can (for some reason) cause DNS resolution issues for some users, in some web browsers. Probably depends on exactly how your network is set up. 

You can use `hostnamectl` to set a custom hostname.

**Comment by RedBearAK** [comment]
@patchedsoul 

Here's another BTW: You should find that if you manually open/run the "Toshy Tray Icon" app from your app launcher after logging into Hyprland, a few seconds later the Toshy services should start working normally. That's because the tray icon app also runs one of the helper commands that the autostart item will run, to give the systemd services access to the environment variables.
