### ISSUE TITLE
[BUG]  Holding shift and clicking to highlight text does not work

### ISSUE THREAD

**Issue by dpoll** [RedBearAK/toshy#445]
```
Bare metal or virtual machine: bare metal
(If in VM, which VM software): None

Linux distro name:  fedora
Distro version:  41
Distro variant:  workstation
X11/Xorg or Wayland:  wayland
Desktop environment(s):  gnome
DE version(s):  47

Keyboard type (IBM, Chromebook, Windows, Apple):  Windows
Keyboard device name (try 'toshy-devices'):  AT Translated Set 2 keyboard  
```

* * *

Problem observed:
In a text editor, I want to highlight a block of text. I place my cursor at the top of the text and then while holding shift, I click at the bottom of the text block with my mouse. With Toshy enabled, this does not highlight the text. I am still able to clock and drag with my mouse to highlight multi-line text.

I tested this by disabling Toshy, confirming that I am able to shift-click to highlight text. Then I restarted Toshy and was unable to do this. Testing was in VScode, Text Editor and Zed. Toshy is otherwise working fine on my system.

**Comment by RedBearAK** [comment]
@dpoll 

This should fix you up. But be sure and read the FAQ entry after this one as well. 

https://github.com/RedBearAK/toshy/wiki/FAQ-(Frequently-Asked-Questions)#modclicking-blocked-by-keymapper-suspend-timeout

**Comment by dpoll** [comment]
Thank you for the response! Setting `suspend` to 0.1 fixes it for me.
