### ISSUE TITLE
[BUG] Slack: Alt+left/right quickly shows window menu without moving cursor

### ISSUE THREAD

**Issue by SebCorbin** [RedBearAK/toshy#447]
```
- Bare metal 

Linux distro name: ubuntu
Distro version: 22.04
Distro variant: None
X11/Xorg or Wayland: X11 
Desktop environment(s): gnome
DE version(s): 46

Keyboard type: Apple (USB)
Keyboard device name: Apple Inc. Apple Keyboard
```

* * *

Problem observed:

When launching Slack (the "native" app from snap, which seems to be based on Electron) and after typing a message, if you want to navigate between words using alt+left/right the window menu would gain focus and move before hiding, and the focus would change 1 time over 2.

Here's a short GIF to explain
![slack](https://github.com/user-attachments/assets/49baf250-8657-4c1a-a7c2-927313441bec)

**Comment by RedBearAK** [comment]
@SebCorbin 

The Electron apps are certainly a pain, unless you can find a way to disable the menu activation when the app sees the `Alt` key code. 

You're on an Apple keyboard, so I assume by "Alt+Left/Right" you mean you're using the physical Option/Alt key, which is indeed `Alt` under Toshy's modmapping. 

There are some things you can do to mitigate the problem in the VSCode variants, which are all Electron-based. But I'm not sure if any of that will be relevant to the Slack app. I've never used it. 

Check out this FAQ entry, and the one above it (and maybe also the one below it, which links to a Wiki page): 

https://github.com/RedBearAK/toshy/wiki/FAQ-(Frequently-Asked-Questions)#vscodes-and-firefox-menu-stealing-focus-when-hitting-optionalt

One of the fixes for the VSCodes involves potentially remapping some shortcuts internally: 

https://github.com/rbreaves/kinto/blob/master/linux/vscode_keybindings.json

If that's not something that can be done in the Slack app, it may be difficult to fix this.

**Comment by RedBearAK** [comment]
I tried to test the app on my own system (Fedora 40 KDE) but immediately realized that it wasn't having the focus stealing menu issue because the Slack app exports its menu bar to the Global Menu widget that I have in my top/menu bar in Plasma. I have Plasma set up to look and act like macOS/GNOME, but with the top bar auto-hidden most of the time to get more vertical screen space. 

Soooo, that's probably not very useful to you, but it is a potential "fix" for some people. 

I poked around in the Slack app preferences and I don't see anything at all about changing keyboard shortcuts within the app. That means any fix will probably have to be external. 

One potential option that I've never really explored before is having a special modmap for Slack that removes the `Alt` key from the keyboard and replaces it with something innocuous like `F19`, then a keymap that will remap `F19+[key]` combos onto `Alt+[key]` combos that would hopefully not trigger the menu bar. 

Would you be able to make a list of shortcut combos involving `Alt` that you would need to be functioning, other than the "wordwise" shortcuts like `Alt+Left/Right`? The keymap could always have more remaps added to it later. 

In order to test something like the modmap idea, I would need to set up Slack in a VM or log out of Plasma and try to test Slack in GNOME. Which I do still actually have on my Fedora system. 

Might take a while to figure out exactly what to do here that would be effective and practical.

**Comment by SebCorbin** [comment]
I've poked around the Slack files, but have not found any JSON related to Electron, so I'm not sure there's a way to set `customMenuBarAltFocus` but I will try some ideas

**Comment by RedBearAK** [comment]
I was able to configure a solution that doesn't activate the menu either before or after the shortcuts are used. It's a little complicated but I think it's probably the only way to get the Slack menu to stop stealing focus. Basically we have to keep the Slack window from seeing the Alt key event at all. 

This actually may end up being applicable to the other apps like VSCodes and Firefox that have menus that keep stealing focus, but it will depend on how many shortcuts will need to be remapped. 

The strategy involves creating a new modifier key, assigned to a safe key code like `F24`, and then making the key that would normally be `Alt` instead be this new modifier key (when we are in the Slack window). I'll probably call the modifier `Hyper` in the examples, but the alias of the new modifier could be anything, within reason. Then all you have to do is remap `Hyper+Left/Right` to `Ctrl+Left/Right` to perform the correct action. 

This will take a little while to write up correctly.

**Comment by RedBearAK** [comment]
Follow these instructions to edit your `toshy_config.py` file, found at this path: 

```
~/.config/toshy/toshy_config.py
```

There is a menu item in the tray icon menu to quickly open the Toshy config folder location. 

Changes should be made only within the marked "slices" in the config file, or reinstalling Toshy will overwrite the changes, and they would only exist in a backup folder. 

I decided to call the new modifier `Crazy` to avoid conflicting with any possible usage of `Hyper`, which is often remapped onto a set of multi-modifier combos for special functions like workspace navigation or window snapping/resizing. 

## Create new modifier alias

Insert this in the protected editable slice tagged with `keymapper_api`: 

```py
# Create a new "Crazy" modifier key alias on F24
Modifier("CRAZY", aliases=["Crazy"], key=Key.F24)
```

## Create modmap(s) to turn key in Option/Alt position into F24

Insert this in the protected editable slice tagged with `exclude_kpad_devs`: 

```py
modmap("Slack fix - Apple kbd", {
    # Convert the Alt key into F24 for use as a modifier, on Apple keyboards, only in Slack app
    Key.LEFT_ALT: Key.F24,
}, when = lambda ctx:
    cnfg.screen_has_focus and
    isKBtype('Apple')(ctx) and
    matchProps(clas="^Slack$")(ctx)
)

modmap("Slack fix - Windows kbd", {
    # Convert the Alt key into F24 for use as a modifier, on Windows keyboards, only in Slack app
    Key.LEFT_META: Key.F24,
}, when = lambda ctx:
    cnfg.screen_has_focus and
    isKBtype('Windows')(ctx) and
    matchProps(clas="^Slack$")(ctx)
)
```


## Remap combos with new modifier back to useful combos

Insert this in the protected editable slice tagged with `user_apps`: 

```py
keymap("Slack fix", {
    # "Crazy" modifier added specifically to keep Slack window from seeing "Alt" modifier
    C("Crazy-Left"):            C("C-Left"),                    # wordwise - move to left word
    C("Crazy-Right"):           C("C-Right"),                   # wordwise - move to right word
}, when = lambda ctx:
    cnfg.screen_has_focus and
    matchProps(clas="^Slack$")
)
```

## Save config file and restart Toshy services

The best thing to do after making changes like this to the config file is to run `toshy-debug` in a terminal, to make sure no syntax errors were made. Then if everything appears to be working correctly, you can later restart the Toshy services from the tray icon, or with the command `toshy-services-restart`. 

It takes about 7 seconds for the keymapper to fully start up. It's best to avoid touching the keyboard while the keymapper starts. The initial debugging output in the terminal will stop, and then the keymapper will be ready to accept input. 

After this change, any other shortcut combos involving the `Alt` key that need to work in the Slack window will have to be added to the keymap as additional remaps, remapping the `Crazy` modifier combo to the necessary combo to perform the action. 

Let me know how this goes.

**Comment by SebCorbin** [comment]
That work for not losing focus but `alt`+`backspace` for example does not remove the whole word but a letter

**Comment by RedBearAK** [comment]
Yeah, I figured there would be other wordwise and similar shortcuts that would need to be added to the keymap. Like this stuff: 

```py
keymap("Wordwise - not vscode", {
    # Wordwise remaining - for Everything but VS Code
    C("Alt-Left"):              C("C-Left"),                    # Left of Word
    C("Alt-Shift-Left"):        C("C-Shift-Left"),              # Select Left of Word
    C("Alt-Right"):             C("C-Right"),                   # Right of Word
    C("Alt-Shift-Right"):       C("C-Shift-Right"),             # Select Right of Word
    C("Alt-Shift-g"):           C("C-Shift-g"),                 # View source control
...
```

And this is from the "General" keymap, which should give a good idea of that combos to remap onto for other things: 

```py
...
    # Wordwise
    C("RC-Left"):               C("Home"),                      # Beginning of Line
    C("Shift-RC-Left"):         C("Shift-Home"),                # Select all to Beginning of Line
    C("RC-Right"):              C("End"),                       # End of Line
    C("Shift-RC-Right"):        C("Shift-End"),                 # Select all to End of Line
    C("RC-Up"):                 C("C-Home"),                    # Beginning of File
    C("Shift-RC-Up"):           C("C-Shift-Home"),              # Select all to Beginning of File
    C("RC-Down"):               C("C-End"),                     # End of File
    C("Shift-RC-Down"):         C("C-Shift-End"),               # Select all to End of File
    C("Super-Backspace"):       C("C-Backspace"),               # Delete Left Word of Cursor
    C("Super-Delete"):          C("C-Delete"),                  # Delete Right Word of Cursor
    C("RC-Backspace"):          C("C-Shift-Backspace"),         # Delete Entire Line Left of Cursor
    C("Alt-Delete"):            C("C-Delete"),                  # Delete Right Word of Cursor
    C("Shift-Alt-Backspace"):   C("C-Backspace"),               # Delete word left of cursor
    C("Shift-Alt-Delete"):      C("C-Delete"),                  # Delete word right of cursor
...
```

**Comment by RedBearAK** [comment]
Ah, found the `Alt-Backspace` shortcut in a different keymap. Apparently it's different on a Chromebook or IBM keyboard (these are inherited from Kinto, I've never actually touched a Chromebook and haven't seen an IBM keyboard in decades). 

```py
# Overrides to General GUI shortcuts for specific keyboard types
keymap("GenGUI overrides: Chromebook/IBM", {
    # In-App Tab switching
    C("Alt-Tab"):              [iEF2NT(),bind,C("C-Tab")],          # Chromebook/IBM - In-App Tab switching
    C("Alt-Shift-Tab"):        [iEF2NT(),bind,C("C-Shift-Tab")],    # Chromebook/IBM - In-App Tab switching
    C("Alt-Grave") :           [iEF2NT(),bind,C("C-Shift-Tab")],    # Chromebook/IBM - In-App Tab switching
    C("RAlt-Backspace"):        C("Delete"),                        # Chromebook/IBM - Delete
    C("LAlt-Backspace"):        C("C-Backspace"),                   # Chromebook/IBM - Delete Left Word of Cursor
}, when = lambda ctx:
    (   isKBtype('Chromebook', map="gengui ovr cbook")(ctx) or 
        isKBtype('IBM', map="gengui ovr ibm")(ctx) ) and
    matchProps(not_clas=remoteStr)(ctx)
)
keymap("GenGUI overrides: not Chromebook", {
    # In-App Tab switching
    C("Super-Tab"):            [iEF2NT(),bind,C("C-Tab")],          # Default not-chromebook
    C("Super-Shift-Tab"):      [iEF2NT(),bind,C("Shift-C-Tab")],    # Default not-chromebook
    C("Alt-Backspace"):         C("C-Backspace"),                   # Default not-chromebook
}, when = lambda ctx:
    not isKBtype('Chromebook', map="gengui ovr not cbook")(ctx) and
    matchProps(not_clas=remoteStr)(ctx)
)
```

**Comment by RedBearAK** [comment]
Not sure what else to add to this. I added everything from the above keymaps that involve the `Alt` key. 

```py
keymap("Slack fix", {
    # "Crazy" modifier added specifically to keep Slack window from seeing "Alt" modifier

    # Wordwise shortcut remaps for Slack menu focus stealing fix
    C("Crazy-Left"):            C("C-Left"),                    # Move to left word boundary
    C("Crazy-Right"):           C("C-Right"),                   # Move to right word boundary

    C("Crazy-Shift-Left"):      C("C-Shift-Left"),              # Select word left of cursor
    C("Crazy-Shift-Right"):     C("C-Shift-Right"),             # Select word right of cursor

    C("Crazy-Backspace"):       C("C-Backspace"),               # Delete word left of cursor
    C("Crazy-Delete"):          C("C-Delete"),                  # Delete word right of cursor

    C("Shift-Crazy-Backspace"): C("C-Backspace"),               # Delete word left of cursor
    C("Shift-Crazy-Delete"):    C("C-Delete"),                  # Delete word right of cursor

}, when = lambda ctx:
    cnfg.screen_has_focus and
    matchProps(clas="^Slack$")
)
```

**Comment by SebCorbin** [comment]
Considering this as closed, thanks again !

**Comment by helloboyxxx** [comment]
I have the same issue. I followed this thread and (almost) solved this problem. My remaining puzzle is the following: when I press `alt` first and then press the arrow key, everything works perfectly. However, If I press the arrow key first and then the `alt` key, the shortcut won't work as expected. (Can also try alt + arrow then release alt then press alt.) 
The expected behavior is that pressing arrow then alt should also perform word level jump. 
Is it possible to fix this?

For vscode, I also tried this: 
> Check out this FAQ entry, and the one above it (and maybe also the one below it, which links to a Wiki page):
> 
> https://github.com/RedBearAK/toshy/wiki/FAQ-(Frequently-Asked-Questions)#vscodes-and-firefox-menu-stealing-focus-when-hitting-optionalt

It turns out that this solution works better (it also supports `alt + up/down` for moving one line around). But the problem I observed remains.

**Comment by RedBearAK** [comment]
@helloboyxxx 

> My remaining puzzle is the following: when I press alt first and then press the arrow key, everything works perfectly. However, If I press the arrow key first and then the alt key, the shortcut won't work as expected. (Can also try alt + arrow then release alt then press alt.)

I have never in my lifetime thought of a keyboard shortcut as anything but a sequence of keys that start by first holding down a "modifier" key to change the behavior of a later key press, and I am pretty sure the keymapper logic can't see the keys as a "combo" if the sequence of the keys is inverted like you describe. 

I tried what you're saying without the keymapper running (with the physical Ctrl key pressed after the arrow key). It seems to work, but the repeating of the arrow key when the modifier is not involved makes this an operation that makes no sense to me. At least in Linux, unless you have key repeats entirely disabled in your keyboard settings. 

Perhaps this idea makes more sense in macOS, but I thought the arrow keys were allowed to repeat, unlike all the normal letter/number keys (which in macOS do not repeat when held down, unlike Windows and Linux). Even if the arrow keys didn't repeat in macOS, I can't imagine why you'd want to do keyboard shortcuts that way. 

> The expected behavior is that pressing arrow then alt should also perform word level jump.

I just fired up a MacBook Air with Sonoma and tried the suggested inverted shortcut in TextEdit. The arrow keys repeat more slowly than on my Linux machine, but it's still not something I would ever find useful. It mixes the repeating action of the arrow key with the wordwise shortcut action of Option+Arrow. 

> Is it possible to fix this?

At the moment I'm afraid I can't think of any way to make inverse-order shortcuts work with this keymapper. I don't know if there are other Linux keymappers with logic that could handle that. There are certainly no other projects like this besides the original project I based the config file on (Kinto) that do anything besides moving some modifiers around and maybe fixing a couple of the most basic general shortcuts to work like macOS. 

If you find Toshy useful I think you'll need to get used to the idea that shortcut combos require always pressing any modifier keys in the combo before pressing the non-modifier key.

**Comment by helloboyxxx** [comment]
Thank you @RedBearAK for your detailed response and all your hard work!!! I enjoy Toshy a lot!

As you mentioned the inverse-order shortcuts seems very weird. I just observed that it is not because I press the arrow first, but it is because I am using combinations for the arrow key. Specifically, I am using a 60% keyboard (Keychron K12), where the logical `Left arrow` corresponds to a physical `fn1 + M`. So, physically I need to press `option + fn1 + M` to trigger the `Ctrl - Left` shortcut, while `fn1 + option + M` is treated as `Left` only. 

I am sure this is not a common issue. I will try to fix my hand instead :)

![keychron k12](https://github.com/user-attachments/assets/83481be9-f439-4da8-829a-2b23025956d3)

**Comment by RedBearAK** [comment]
@helloboyxxx 

> I am using a 60% keyboard (Keychron K12), where the logical Left arrow corresponds to a physical fn1 + M. So, physically I need to press option + fn1 + M to trigger the Ctrl - Left shortcut, while fn1 + option + M is treated as Left only.

Ah. That's certainly a different story. Either the key event from the `fn1` key is seen by the keymapper or the order just causes some different key events to come out of the keyboard. I'm sure it will all work as long as it's done in the right order. 

> For this keyboard, it is detected as a Win setup. In the debug mode the left alt key has no output when pressed.
Then, I tried to manually set the keyboard type to MacOS. Looks everything works well now!

Yeah, anything that doesn't have "Apple" or "Magic" in the device name will generally be assumed to be a "Windows" type keyboard, according to the relatively simple keyboard type detection logic in Toshy's config file. If it's acting in a "Mac" mode with the Meta/Super/Win/Cmd key right next to the Space bar, that does mean you'll need to override its detected keyboard type. 

Be sure to make the "Apple" type permanent for that specific device by following the FAQ entry about keyboard types. The menu item is just meant to temporarily test the type change. 

https://github.com/RedBearAK/toshy/wiki/FAQ-(Frequently-Asked-Questions)#my-keyboard-is-not-recognized-as-the-correct-type

> I enjoy Toshy a lot!

👍🏽

**Comment by deviant** [comment]
> I tried to test the app on my own system (Fedora 40 KDE) but immediately realized that it wasn't having the focus stealing menu issue because the Slack app exports its menu bar to the Global Menu widget that I have in my top/menu bar in Plasma. I have Plasma set up to look and act like macOS/GNOME, but with the top bar auto-hidden most of the time to get more vertical screen space. So I have no issue with `Alt-Left/Right` shortcuts, because something else is managing the menu bar, instead of the main Slack window.
> 
> Soooo, that's probably not very useful to you, but it is a potential "fix" for some people.

Sorry for necroing, but I just wanted to say thank you for sharing this solution. I prefer it to the other solution (of the virtual modifier & associated remapping), as it's much simpler to set up, works across all Electron apps automatically, and even matches my preference for how the menu bar is positioned. As it happens, I'd previously tried out the Global Menu widget, but ended up removing it pretty quickly, as almost none of the applications I use seem to support it. (Something to do with Wayland incompatibility?) I suppose I'll live with that existing in a half-functioning state, if it lets me use my Alt key in peace...

**Comment by SebCorbin** [comment]
FYI Slack recently modified the way it displays its title : `[channel_name] (Channel) - [workspace] - Slack`

The fix must be adapted to remove `^` in `matchProps(clas="^Slack$")`

**Comment by RedBearAK** [comment]
It will probably work just to take the caret out, but more technically correct would be like this:
```
matchProps(clas=".*Slack$")
```

So it matches any number of characters in front of Slack, keeping the `$` for end of line. 

I don't think the Slack keymap ended up in the default Toshy config, so this would just be an adjustment for your custom keymaps. 

Thanks for reporting on that change, @SebCorbin .
