### ISSUE TITLE
[BUG] Cmd+Left/Right (Home/End wordwise shortcuts) don't do page navigation in web browsers

### ISSUE THREAD

**Issue by MZhuvka** [RedBearAK/toshy#486]
```
Bare metal or virtual machine: Bare metal, M1 MacBook
(If in VM, which VM software): None

(Try running 'toshy-env' in a terminal to fill out the following fields...)

Linux distro name: Fedora (Asahi Linux)
Distro version: 41
Distro variant: kde
X11/Xorg or Wayland: Wayland
Desktop environment(s): kde
DE version(s): 6

Keyboard type (IBM, Chromebook, Windows, Apple): Apple
Keyboard device name (try 'toshy-devices'): Apple Internal Keyboard / Trackpad 
```

* * *

Problem observed:
Forward and Back keyboard shortcuts (that function as these buttons in the browser)
![image](https://github.com/user-attachments/assets/abb8d62c-e0a6-4842-8dd6-2ab2434bea8c)
don't function as expected

Expected behaviour:
Cmd+left = Back
Cmd+right = Forward

Actual behaviour:
Cmd+left = Home
Cmd+right = End

Doesn't work when using option or control either. Would be nice to have an ability to toggle these(possibly per app), or use them with option.

**Comment by RedBearAK** [comment]
@MZhuvka 

> Doesn't work when using option or control either. Would be nice to have an ability to toggle these(possibly per app), or use them with option.

The keymapper does app-specific behavior for a lot of individual apps, and for groups of known apps like many web browsers (both Firefox and Chrome variants). 

Soooo... I have no idea how to respond to this without more details. 😕 

In exactly which application(s) does the expected Back/Forward shortcut not work? The behavior will be different depending on the app. 

You can use the diagnostic dialog shortcut to check the app class of each affected window. 

The physical equivalent on an Apple keyboard: 

```
Shift+Option+Cmd+I,I (the "I" key must be double-tapped quickly)
```

**Comment by MZhuvka** [comment]
![image](https://github.com/user-attachments/assets/0f1cd856-9672-45ad-9911-0b0f1d87eca7)
So, it recognizes that Firefox is a web browser, but stil cmd+arrows work like home & end.

**Comment by RedBearAK** [comment]
Another way to look at this is if you override the shortcuts and ever attempt to use the `Home/End` wordwise shortcuts while editing text, you may unfortunately be unexpectedly navigated away from the page where you are editing text, because the shortcuts will have been remapped to page navigation, and that will be their only function in Firefox windows. 

So it's not just that you wouldn't get the usual `Home/End` functions while editing text. I don't recommend doing the override unless you literally never use wordwise `Home/End` shortcuts.

**Comment by MZhuvka** [comment]
I mainly use `Fn+Left/Right` for home and end, so using an override most likely won't affect anything for me. But your alternative also works, so thanks!

**Comment by RedBearAK** [comment]
Sounds good. I'll consider this closed since the config is designed to work this way, and the alternative override has been presented. You'll have to "@" me or open a new issue if you have another problem. Don't hesitate to do so. 👍🏽
