### ISSUE TITLE
Shift+Cmd+Click and Cmd+Click in Firefox not working

### ISSUE THREAD

**Issue by burakerdem** [RedBearAK/toshy#75]
```
Bare metal or virtual machine: Baremetal
(If in VM, which VM software): None

(Try running 'toshy-env' in a terminal.)

Linux distro name: DEBIAN
Distro version: 12
X11/Xorg or Wayland: X11
Desktop environment(s): XFCE

Any DE(s) tried with Wayland?: 

Keyboard type (IBM, Chromebook, Windows, Apple): Windows
Keyboard device name (try 'toshy-devices'): K380 Keyboard
```

These terminal commands may provide helpful info:

- toshy-services-log  
- toshy-services-status  
- toshy-config-start-verbose  
- toshy-devices
- toshy-env

Problem observed:  Shift+Cmd+Click and Cmd+Click on a link not working in Firefox 116.0.3 (64-bit). Shift+Cmd+Click should open the link in a new tab where Cmd+Click should open in a new background tab but both those shortcuts not working. It always opens the link in the current tab. **ONLY** the following settings are active;

* Alt_Gr on Right Cmd key
* Disable Option-key Special Characters
* * *

**Comment by RedBearAK** [comment]
@burakerdem 

Check the FAQ item in the README about the “suspend” timeout. If you can hold the keys for at least one second before clicking and it works that’s your issue. 

Reducing the suspend timeout may require the Firefox menu fix described just below that in the README.

**Comment by burakerdem** [comment]
Well, first thank you for leading me the correct way.

Yes, it works if I hold the Shift+Cmd for at least 1 second and then click the link. But the problem is that I don't use a trackpad but a mouse. The README says the following;

*The suspend timer scheme works well for mouse usage, letting you do things like Alt+click, Ctrl+click/Cmd+click and Shift+click, but with a touchpad, you may need to reduce the one-second timer to zero or 0.1 seconds in order for those operations to work as you would expect.*

It seems like this might not be true in my case because I'm using a mouse, not a trackpad. It's not a big deal and I'm going to reduce the one-second timer to zero but I wanted to inform you that the mouse is also affected by this issue.

Thanks.

**Comment by RedBearAK** [comment]
@burakerdem 

You're right, I need to modify the FAQ entry. I was operating from a limited understanding of the situations where the suspend timeout works and doesn't work. Other users have said they had the same problem, and were using a regular mouse. 

I didn't write the keymapper, and I'm not that familiar with how that part of it works. 

Thanks for trying Toshy. 👍🏽

**Comment by RedBearAK** [comment]
Thanks for your report. I rewrote the FAQ entry so it should be less confusing. 

https://github.com/RedBearAK/toshy#modclicking-blocked-by-keyszer-suspend-timeout

Closing as resolved.

**Comment by pythoninthegrass** [comment]
Didn't seem to work for me. Unable to mod/cmd click links to open in a new tab as expected.

To verify, edit the `~/.config/toshy/default-toshy-config.py` file to match
```py
timeouts(
    multipurpose        = 1,      # default: 1 sec
    suspend             = 0.1,      # default: 1 sec, try 0.1 sec for touchpads/trackpads
)
```
then run `toshy-services-restart`? Tried using 0 as well with the same results.

(Also, the link moved to the [wiki](https://github.com/RedBearAK/toshy/wiki/FAQ-(Frequently-Asked-Questions)#modclicking-blocked-by-keymapper-suspend-timeout))

**Comment by RedBearAK** [comment]
> To verify, edit the `~/.config/toshy/default-toshy-config.py` file to match

This line in your comment is peculiar. The name of your config file should be `toshy_config.py` in the main folder (placed there by the installer script), and the files in the “default-toshy-config” sub-folder are just backups/originals. Sounds like you are somehow editing a file the keymapper won’t be looking for, thus having no effect when you change the setting.

**Comment by RedBearAK** [comment]
> To verify, edit the ~/.config/toshy/default-toshy-config.py ~/.config/toshy/default-toshy-config/default-toshy-config.py file to match

@pythoninthegrass 

To be clear, the edited line is still referencing the `default-toshy-config` sub-folder in quite a confusing way. There should be no need to be referring to or touching the files in that folder unless you somehow messed up your `~/.config/toshy/toshy_config.py` file and can't figure out how to fix it. In which case you can go into that folder and _make a copy_ of the version of the default config that corresponds to how you use Toshy: 

```sh
default-toshy-config/toshy_config.py
```

This is the original default config that gets copied to the main folder by the Toshy installer. It does all the Mac-like remaps. 

```sh
default-toshy-config/toshy_config_barebones.py
```

This one gets copied to the main folder and renamed "toshy_config.py" if you use the "barebones" installer option to avoid all the Mac-like keyboard shortcuts and make your own clean config:

```sh
./setup_toshy.py install --barebones-config
```

But generally nobody should need to look in that `default-toshy-config` folder at all. If you have a syntax error in the config, the verbose debugging output will normally specify the exact line and location that's causing the problem. 

```sh
toshy-config-verbose-start
```
