### ISSUE TITLE
[BUG] Install fails on Pop!_OS 22.04

### ISSUE THREAD

**Issue by hyuri** [RedBearAK/toshy#88]
```
Bare metal or virtual machine: 
Bare metal

(Try running 'toshy-env' in a terminal.)

Linux distro name: 
Distro version: Pop!_OS 22.04
X11/Xorg or Wayland: X11/Xorg
Desktop environment(s): Gnome 42.9

Any DE(s) tried with Wayland?: No

Keyboard type (IBM, Chromebook, Windows, Apple): Windows
Keyboard device name (try 'toshy-devices'): ?
```

These terminal commands may provide helpful info:

- toshy-services-log  
- toshy-services-status  
- toshy-config-start-verbose  
- toshy-devices
- toshy-env

### Problem observed:  
```
§  Installing native packages for this distro type...
================================================================================

ERROR: No list of packages found for this distro: 'pop'
Installation cannot proceed without a list of packages. Sorry.
Try some options in "./toshy_setup.py --help"
```

**Comment by RedBearAK** [comment]
Oh dear. I shifted from using the distro name to the "id", and it looks like Pop!_OS is unexpectedly different. 

Should work if you do it this way: 

```sh
./toshy_setup.py --override-distro popos
```

Thanks for reporting.

**Comment by RedBearAK** [comment]
This issue with using the wrong ID for the distro will also affect a couple of general shortcuts in the config file specific to Pop!_OS. If you re-install from this zip of the beta branch everything should be fixed. 

[toshy-dev_beta_pop_fix.zip](https://github.com/RedBearAK/toshy/files/12590797/toshy-dev_beta_pop_fix.zip)

I don't want to merge some other changes from this into the main branch just yet. But they should be completely irrelevant to running Toshy on Pop!_OS. 

Just did a test install on Pop!_OS 22.04 and it is working as expected.

**Comment by hyuri** [comment]
Thank you for fixing it and so quickly!
It installed and seems to be running well, except for a few little things (I'll report them).
