### ISSUE TITLE
[BUG] Key + Mouse actions don't work without holding the key for a few seconds

### ISSUE THREAD

**Issue by hyuri** [RedBearAK/toshy#89]
```
Bare metal or virtual machine: 
(If in VM, which VM software): Bare metal

(Try running 'toshy-env' in a terminal.)

Linux distro name: 
Distro version: Pop!_OS 22;04
X11/Xorg or Wayland: X11/Xorg
Desktop environment(s): Gnome 42.9

Any DE(s) tried with Wayland?: No

Keyboard type (IBM, Chromebook, Windows, Apple): Windows
Keyboard device name (try 'toshy-devices'): Dell KB216 Wired Keyboard
```

These terminal commands may provide helpful info:

- toshy-services-log  
- toshy-services-status  
- toshy-config-start-verbose  
- toshy-devices
- toshy-env

Problem observed:  
Key + Mouse actions such as Command (physical Alt) + Click (to open link in new tab, or app in new window) and Control (physical Ctrl) + Scroll Up/Down (over the Gnome panel or Dash-To-Dock, to switch to next/previous workspace) don't work unless I hold the key for a few seconds (1? 2? 3?) first.
I thought it was the suspend thing that's mentioned in the docs and changed it to 0.1s in toshy_config.py but nothing changed (do I have to restart anything after making that change?)

Any idea what might be the issue?

**Comment by RedBearAK** [comment]
Oh, good job finding the FAQ entry. Does it not make clear that when you edit the config file you need to restart Toshy? Just use the top item from the tray icon menu. 

You should be good after that.

**Comment by hyuri** [comment]
Ah, nice!

Yes, it wasn't clear, in that section. I just found a mention of it `(Adding or changing shortcuts in the config file will still require restarting the keymapper, which I've tried to make as easy as possible.)`, in the "General improvements over Kinto" section.

Thanks!

**Comment by hyuri** [comment]
By the way, to restart, should I click on Re/Start Toshy Services, or Re/Start Toshy Script?

**Comment by RedBearAK** [comment]
> By the way, to restart, should I click on Re/Start Toshy Services, or Re/Start Toshy Script?

Yeah, that's a little ambiguous, isn't it? The "Script" items are for circumstances where there is a need to run the keymapper launcher script "manually" without using the `systemd` services to manage things. For instance, on a Linux distro that doesn't even have `systemd` installed. 

Normally you want to use the "Services" items. Or the terminal commands `toshy-services-start/stop/restart`. 

And if you need to debug a change to the config file, `toshy-config-verbose-start` will automatically stop the services and run the manual config, then using the menu item to restart the services will automatically terminate the verbose process running in the shell when you're done. They are all kind of designed to work together without too many issues.

**Comment by hyuri** [comment]
Got it!
After restarting, it's working beautifully. Thank you so much!
