### ISSUE TITLE
[BUG] F3 and Esc don't toggle off "Mission Control" in Gnome, F3 only toggles it on

### ISSUE THREAD

**Issue by hyuri** [RedBearAK/toshy#91]
```
Bare metal or virtual machine: 
(If in VM, which VM software): Bare metal

(Try running 'toshy-env' in a terminal.)

Linux distro name: 
Distro version: Pop!_OS 22;04
X11/Xorg or Wayland: X11/Xorg
Desktop environment(s): Gnome 42.9

Any DE(s) tried with Wayland?: No

Keyboard type (IBM, Chromebook, Windows, Apple): Windows
Keyboard device name (try 'toshy-devices'): Dell KB216 Wired Keyboard
```

These terminal commands may provide helpful info:

- toshy-services-log  
- toshy-services-status  
- toshy-config-start-verbose  
- toshy-devices
- toshy-env

Problem observed:
(In Gnome) When I press `F3`, it opens its "Mission Control" (apps + workspaces overview). But pressing `F3` again doesn't close "Mission Control". Neither does the `Esc` key (`Esc` only works if I press it twice).

I can observe 2 things:
1) When I press `F3`, the app that was in focus, loses focus in the dock (Dash-To-Dock extension).
- Before pressing `F3`:
![image](https://github.com/RedBearAK/toshy/assets/18584014/21fa3bd7-dc1b-4a1f-b5d5-a143cc3f5f5d)
- After pressing `F3`:
![image](https://github.com/RedBearAK/toshy/assets/18584014/41d696d9-cc1d-481d-a834-0991905c1e97)
- When I press `Esc` once, the app regains focus in the dock:
![image](https://github.com/RedBearAK/toshy/assets/18584014/21fa3bd7-dc1b-4a1f-b5d5-a143cc3f5f5d) 

At this point, if I press `Esc` again, "Mission Control" (I'm not sure the proper Gnome name) exits.

2) After opening "Mission Control" with `F3`, pressing the Down key brings up a small context menu with two options — "Copy", grayed out, and "Paste", select/highlighted) — over the mini workspaces overview:
![image](https://github.com/RedBearAK/toshy/assets/18584014/1cfbf94b-0520-473a-8fdd-369701805377)

If I press `Esc` once then press the Down key, the small menu doesn't show up.

---
This issue began happening after I installed Toshy and Search Light (Gnome Extension), but I've disabled  Search Light and it still happens. Also, the issue doesn't happen if I open "Mission Control" using a hot corner. So seems to be Toshy-related. Unless I'm missing something.

Worthy noting, I think I was the one who set up the shortcut manually:
![image](https://github.com/RedBearAK/toshy/assets/18584014/86c6da9c-b99c-4441-a9b7-d092ad1d86e2)

And I have a few extensions that modify the look and behavior of the "Mission Control" and "Launchpad", especially one called "Start Overlay in Application View" that separates these two (by default, in Gnome 42, they are combined). But again, the issue wasn't happening before I installed Toshy, so seems related.

**Comment by RedBearAK** [comment]
Can you run `toshy-config-verbose-start` and see what happens when you press F3 and then Escape? 

At the moment I have no idea what's happening. There are a couple of remaps of F3, one in a keymap for VSCodes and one in a keymap for Sublime Text 3. All the other instances of F3 are part of combos. 

Get some debug output and we'll see what the deal is.

**Comment by RedBearAK** [comment]
Here's what I'm seeing. 

- Nothing unusual about what the keys do with Toshy enabled.
- The behavior is the same with Toshy disabled.
- The search field uses the first Escape key press to "clear" the search field.
- The "Search" shortcut appears to open the GNOME "Overview".
- The Overview also has its own shortcut (Show the overview).
- The "Search" shortcut will not "toggle" (close the Overview).
- The Overview shortcut will "toggle" (close the Overview).

I think you want to switch your F3 shortcut to the "Show the overview" item. Then it should work more like you expect. 

And it doesn't appear to have anything to do with Toshy. As far as I can tell.

**Comment by RedBearAK** [comment]
From some of the things you describe, you might want to think about restarting or at least logging out. Some GNOME shell extensions can leave pieces of themselves in memory and cause weird effects even when they seem to be disabled or removed.

**Comment by hyuri** [comment]
Ahh, that was it — "Show the overview"! That did the trick! So many similar shortcuts... got me confused. Thank you!
