### ISSUE TITLE
(Question) I'm having issues running the installer on Fedora Asahi Linux

### ISSUE THREAD

**Issue by genericapplesauce** [RedBearAK/toshy#98]
Hello, I'm assuming this is just some weird thing with Python on Asahi Linux, but I'm having an issue on the `Installing/upgrading Python packages...` step. Looks like pip is having trouble with installing `pywayland`. I've attached the output of my attempt here:
[toshy.log](https://github.com/RedBearAK/toshy/files/13170079/toshy.log)

**Comment by RedBearAK** [comment]
@genericapplesauce 

To start, I haven't ever taken a look at Asahi Linux to see what the native package list would need to look like, what what package manager it uses. So that will probably be the first problem. 

I'm confused by the log a bit. Is it pieced together from different runs of the installer? It seems to be doing things that could not be happening in that sequence. 

Do you have any idea why the environment info says it's running the installer on Fedora 39? Are you trying to install in a container with distrobox or something similar? Because as of now I don't think that will work. 

We may be able to make it work, but I'll need a lot more information about the environment you're trying to use.

**Comment by RedBearAK** [comment]
@genericapplesauce 

I didn't realize that Asahi is specifically for the Apple Silicon Macs. I thought it was just a variant of an existing Linux distro. 

So I would guess that being identified as Fedora 39 would make sense if you installed with the command from here: 

https://fedora-asahi-remix.org/

It's likely that there may be an issue with some dependency not being available or compatible with the Apple Silicon platform yet, but from the disjointed log output it is difficult to tell what it might be. 

You can attempt to install from the v23.08 release state of the project, which I think did not yet use the branch of the keymapper with code meant to work on Hyprland and use `pywayland`, so it shouldn't try to install that pip package. Maybe that would allow you to get through the install. 

https://github.com/RedBearAK/toshy/releases/tag/Toshy_v23.08

**Comment by genericapplesauce** [comment]
Thanks for the quick reply! Sorry for not providing more info on the environment, that's my bad. I just installed it today so I barely know what's going on myself.

>So I would guess that being identified as Fedora 39 would make sense if you installed with the command from here:
https://fedora-asahi-remix.org/

Yep, I am on the Fedora Asahi Remix.

> I'm confused by the log a bit. Is it pieced together from different runs of the installer? It seems to be doing things that could not be happening in that sequence.

If it helps, that's a log I captured from like my 3rd run of the installer (`./setup_toshy.py 2>&1 | tee ~/toshy.log
`, so err and std are piped together).

>You can attempt to install from the v23.08 release state of the project, which I think did not yet use the branch of the keymapper with code meant to work on Hyprland and use pywayland, so it shouldn't try to install that pip package. Maybe that would allow you to get through the install.
https://github.com/RedBearAK/toshy/releases/tag/Toshy_v23.08

I'll try this and report back, it would be pretty cool to get this working on Asahi ARM Macbooks for obvious reasons!

**Comment by genericapplesauce** [comment]
@RedBearAK It worked perfectly! (I did run `./setup_toshy.py --uninstall` before changing to the v23.08 release)

**Comment by RedBearAK** [comment]
@genericapplesauce 


> If it helps, that's a log I captured from like my 3rd run of the installer (./setup_toshy.py 2>&1 | tee ~/toshy.log , so err and std are piped together).

Ah... weird. Third run makes sense, as all the native packages are already installed. Still seems like some of those things couldn't possibly come out in that order in one run, but I'll do some experimenting of my own. Like the section header about installing native packages is in the log after the whole pip install attempt, which is not how the installer sequence works. 

> Thanks for the help and the quick reply, Toshy seems really cool so far!

I am glad that it works. I'd like to fix the actual problem with the latest version, but I don't have access to a an M-series Mac. Certainly not a "spare" to play with like this. So unless you were up to doing a bunch of test runs to try to figure out the actual issue, I would have no way of making any progress on that. 

It would be possible to do test runs and then re-run the known-working version (v23.08) to get back to a working state in between. If you have to customize anything like the suspend timer value in the config file, the installer is designed to try to retain that customization. And you only need to reboot once, when fixing the input device permissions and adding your user to the right group. 

If you don't have the time for that and just want to use it, enjoy. That's what I made it for. 👍🏽

**Comment by genericapplesauce** [comment]
I don't have a ton of time at the moment, but I would like to help. If you tell me what to do, I'd happily do some testing when I get a chance.

**Comment by RedBearAK** [comment]
This could make the log make a lot more sense, time-wise. It disables the buffering that probably caused the out of order output. 

```sh
python -u ./setup_toshy.py 2>&1 | tee ~/"toshy_setup_$(date +%Y%m%d_%H%M).log"
```

If you could do one run of the most recent zip (not a "release" zip, as I'm always making minor changes to the main branch), that may help. Then I can look it over and see if I'll be able to change something that would help make it work. 

The timestamp will cause it to make a new file each time.

**Comment by RedBearAK** [comment]
You probably don't need to do the `--uninstall` between runs, that's mainly useful if you really want to remove it. Everything should get appropriately overwritten when you run the working version of the installer again.

**Comment by genericapplesauce** [comment]
Here, let me know if that's not quite what you were asking for, but I ran this as `python3` instead of `python` because Asahi doesn't seem to have `python` symlinked to anything. Also, I ran it off of `main` - let me know if downloading the zip was an important aspect of this, and I can run it again. 
[toshy_setup_20231025_2119.log](https://github.com/RedBearAK/toshy/files/13172043/toshy_setup_20231025_2119.log)

**Comment by RedBearAK** [comment]
The log at least makes a lot more sense now, without the out of order buffering. 

In theory it appears to be a simple issue. See if you can get through the install after doing this: 

```sh
sudo dnf install wayland-devel
```

This is the package that provides the missing file the error complains about: /usr/share/wayland/wayland.xml

The fact that the package is missing from the base install is probably down to it being still in alpha/beta stage. I hope.

**Comment by genericapplesauce** [comment]
That did it. Thanks for the support! I have no idea how `pip` works so I didn't realize it can look for system packages and not figure it out for itself. Toshy (and Kinto) might be pretty helpful for current and future Fedora Asahi Linux users, so I really appreciate you taking the time.
[Log for posterity](https://github.com/RedBearAK/toshy/files/13172293/toshy_setup_20231025_2208.log)

**Comment by genericapplesauce** [comment]
Issue resolved: out of the box M1 Macbook Pro running Asahi Linux's current build has a dependency on wayland, run `sudo dnf install wayland-devel` before running the Toshy installer.

**Comment by RedBearAK** [comment]
@genericapplesauce 

Thanks for taking the time to confirm that works. I'll add it to the default package list for the Fedoras. 👍🏽
